Atlas: CoreObject Class Reference
CoreObject Class Reference
Represents a 3D object in the scene, including its geometry, material and every interaction with the scene that it can have. It inherits from GameObject and can have Component classes attached to it for extended functionality.
#include <object.h>
Public Member Functions
CoreObject ()
Function to construct a new CoreObject.
void makeEmissive (Scene *scene, Color emissionColor, float intensity)
Makes the object emissive by attaching a light to it.
void attachVertices (const std::vector< CoreVertex > &newVertices)
Function to attach vertices and update the object's vertex buffer.
void attachIndices (const std::vector< Index > &newIndices)
Function to attach indices and update the object's index buffer.
void attachProgram (const ShaderProgram &program) override
Binds an already compiled shader program for this object.
void createAndAttachProgram (VertexShader &vertexShader, FragmentShader &fragmentShader) override
Builds a shader program from the supplied vertex and fragment sources, then binds it.
void attachTexture (const Texture &texture) override
Adds a texture to the object and makes it available during rendering.
void initialize () override
Performs deferred setup of buffers, shaders, and state.
void refreshPipeline ()
std::optional< std::shared_ptr< opal::Pipeline > > getPipeline () override
void setPipeline (std::shared_ptr< opal::Pipeline > &pipeline) override
void renderColorWithTexture ()
Function to render the object with color and texture.
void renderOnlyColor ()
Function to render the object with only its color.
void renderOnlyTexture ()
Function to render the object with only its texture.
void setColor (const Color &color) override
Sets a solid color override that multiplies with textures.
void setPosition (const Position3d &newPosition) override
Places the object at an absolute position in world space.
void move (const Position3d &deltaPosition) override
Moves the object relative to its current position.
void setRotation (const Rotation3d &newRotation) override
Assigns an absolute rotation to the object.
void setRotationQuat (const glm::quat &quat)
void lookAt (const Position3d &target, const Normal3d &up={0.0, 1.0, 0.0}) override
Rotates the object so its forward vector points towards a target.
void rotate (const Rotation3d &deltaRotation) override
Applies an incremental rotation around the object's axes.
void setScale (const Scale3d &newScale) override
Uniformly scales the object along each axis.
void updateModelMatrix ()
Function that updates the model matrix based on the object's position, rotation, and scale.
void updateVertices ()
Function that updates the object's vertex buffer.
CoreObject clone () const
Function that creates a copy of the object.
void show () override
Shows the object, making it visible in the scene.
void hide () override
Hides the object, making it invisible in the scene.
template<typename T>
void addComponent (T &&existing)
Function that adds a component to the object. The component will have this CoreObject as its parent.
template<typename T>
void addComponent (const std::shared_ptr< T > &component)
void disableDeferredRendering ()
Switches the object to forward rendering by binding default shaders.
Instance & createInstance ()
Creates and returns a new instance for instanced rendering.
void render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline=false) override
Draws the object for the current frame.
void setViewMatrix (const glm::mat4 &view) override
Uploads the active view matrix used for transforming vertices to camera space.
void setProjectionMatrix (const glm::mat4 &projection) override
Uploads the projection matrix that maps camera space to clip space.
Position3d getPosition () const override
Gets the world-space position of the object.
std::vector< CoreVertex > getVertices () const override
Returns a copy of the object's vertex collection.
Size3d getScale () const override
Gets the current non-uniform scale applied to the object.
bool canCastShadows () const override
Reports whether the object is configured to cast shadows.
Rotation3d getRotation () const override
void update (Window &window) override
Performs per-frame updates such as component ticking or buffering synchronization.
bool canUseDeferredRendering () override
Indicates whether the object is eligible for the deferred rendering pipeline.
void onCollisionEnter (GameObject *other) override
void onCollisionExit (GameObject *other) override
void onCollisionStay (GameObject *other) override
void onSignalRecieve (const std::string &signal, GameObject *sender) override
void onSignalEnd (const std::string &signal, GameObject *sender) override
void beforePhysics () override
void onQueryReceive (QueryResult &result) override
Public Member Functions inherited from GameObject
GameObject ()
Construct a new GameObject and assign it a unique ID.
GameObject (const GameObject &other)
GameObject (GameObject &&other) noexcept
GameObject & operator= (const GameObject &other)
GameObject & operator= (GameObject &&other) noexcept
virtual ~GameObject ()
template<typename T>
void addComponent (T &&existing)
Adds a component to the object.
void beforePhysics () override
template<typename U, typename T>
void addTraitComponent (T &&existing)
Adds a trait component to the object. A trait component is a component that is tied to a specific type of GameObject.
template<typename T>
std::shared_ptr< T > getComponent ()
Gets the first component that matches the specified type.
unsigned int getId () override
Returns the unique identifier associated with this object.
void addDependency (GameObject *obj)
std::vector< GameObject * > getDependencies () const
Public Member Functions inherited from Renderable
virtual std::optional< ShaderProgram > getShaderProgram ()
Returns the currently bound shader program, if any.
virtual void setShader (const ShaderProgram &shaderProgram)
Replaces the shader program bound to the renderable.
virtual ~Renderable ()=default
Public Attributes
std::vector< CoreVertex > vertices
The vertices of the object.
std::vector< Index > indices
The indices of the object. These indicate how the vertices are connected to form faces.
ShaderProgram shaderProgram
std::vector< Texture > textures
The textures applied to the object.
Material material = Material()
The material properties of the object.
std::vector< Instance > instances
Vector of instances for instanced rendering. Multiple copies of the object can be rendered with different transforms efficiently.
std::shared_ptr< opal::Pipeline > pipeline
Position3d position = {0.0, 0.0, 0.0}
The position of the object in 3D space.
Rotation3d rotation = {0.0, 0.0, 0.0}
The rotation of the object in 3D space.
Scale3d scale = {1.0, 1.0, 1.0}
The scale of the object in 3D space.
std::shared_ptr< Light > light = nullptr
The light attached to this object if it's emissive. Used for emissive objects created with makeEmissive().
bool castsShadows = true
Variable that determines if the object casts shadows.
bool useDeferredRendering = true
Whether the object should use deferred rendering. When false, the object is rendered in the forward rendering pass.
Public Attributes inherited from GameObject
Rigidbody * rigidbody = nullptr
Public Attributes inherited from Renderable
bool renderDepthOfView = false
Whether the object should be included in depth of field calculations. When true, contributes to blur effects.
bool renderLateForward = false
Whether the object must be moved to the late forward rendering pipeline. Objects flagged here are skipped during the primary forward pass and rendered only after all standard forward elements.
Friends
class Window
class RenderTarget
class Skybox
Additional Inherited Members
Protected Attributes inherited from GameObject
std::vector< std::shared_ptr< Component > > components
std::vector< GameObject * > dependencies
int id
The unique identifier for the object.
Detailed Description
Represents a 3D object in the scene, including its geometry, material and every interaction with the scene that it can have. It inherits from GameObject and can have Component classes attached to it for extended functionality.
Example of a CoreObject
// (Optional) Register resources once, typically at startup
Workspace::get().setRootPath("assets/");
Workspace::get().createResource("textures/brick.png", "Brick",
                               ResourceType::Image);
// Create a simple cube object
CoreObject cube = createBox({1.0, 1.0, 1.0}, Color::red());
cube.setPosition({0.0, 0.5, 0.0});
// Attach a texture by resource name
cube.attachTexture(Texture::fromResourceName("Brick", TextureType::Color));
// Attach default shaders (or supply custom GLSL via fromSource)
VertexShader vs = VertexShader::fromDefaultShader(AtlasVertexShader::Main);
FragmentShader fs =
    FragmentShader::fromDefaultShader(AtlasFragmentShader::Main);
vs.compile();
fs.compile();
cube.createAndAttachProgram(vs, fs);
// PBR-ish material values
cube.material.albedo = Color::red();
cube.material.metallic = 0.0f;
cube.material.roughness = 0.6f;
cube.material.ao = 1.0f;
scene.addObject(&cube);
Definition at line 275 of file object.h.
Constructor & Destructor Documentation
CoreObject()
CoreObject::CoreObject ()
Function to construct a new CoreObject.
Member Function Documentation
addComponent() [1/2]
template<typename T> void CoreObject::addComponent (const std::shared_ptr< T > & component) inline
Definition at line 480 of file object.h.
{
        if (!component) {
            return;
        }
        component->object = this;
        component->atAttach();
        components.push_back(component);
    }
References GameObject::components.
addComponent() [2/2]
template<typename T> void CoreObject::addComponent (T && existing) inline
Function that adds a component to the object. The component will have this CoreObject as its parent.
Template Parameters
T The type of component to add.
Parameters
existing The existing component to add.
Definition at line 469 of file object.h.
{
        using U = std::remove_cvref_t<T>;
        std::shared_ptr<U> component =
            std::make_shared<U>(std::forward<T>(existing));
        component->object = this;
        component->atAttach();
        components.push_back(component);
    }
References GameObject::components, and U.
attachIndices()
void CoreObject::attachIndices (const std::vector< Index > & newIndices)
Function to attach indices and update the object's index buffer.
Parameters
newIndices The indices to attach.
attachProgram()
void CoreObject::attachProgram (const ShaderProgram & program) override virtual
Binds an already compiled shader program for this object.
Reimplemented from GameObject.
attachTexture()
void CoreObject::attachTexture (const Texture & texture) override virtual
Adds a texture to the object and makes it available during rendering.
Reimplemented from GameObject.
attachVertices()
void CoreObject::attachVertices (const std::vector< CoreVertex > & newVertices)
Function to attach vertices and update the object's vertex buffer.
Parameters
newVertices The vertices to attach.
beforePhysics()
void CoreObject::beforePhysics () inline override virtual
Reimplemented from Renderable.
Definition at line 634 of file object.h.
{
        for (auto &component : components) {
            component->beforePhysics();
        }
    }
References GameObject::components.
canCastShadows()
bool CoreObject::canCastShadows () const inline override virtual
Reports whether the object is configured to cast shadows.
Reimplemented from Renderable.
Definition at line 586 of file object.h.
{ return castsShadows; }
References castsShadows.
canUseDeferredRendering()
bool CoreObject::canUseDeferredRendering () inline override virtual
Indicates whether the object is eligible for the deferred rendering pipeline.
Reimplemented from Renderable.
Definition at line 600 of file object.h.
{ return useDeferredRendering; }
References useDeferredRendering.
clone()
CoreObject CoreObject::clone () const
Function that creates a copy of the object.
Returns
(CoreObject) The cloned object.
References CoreObject().
createAndAttachProgram()
void CoreObject::createAndAttachProgram (VertexShader & vertexShader, FragmentShader & fragmentShader) override virtual
Builds a shader program from the supplied vertex and fragment sources, then binds it.
Reimplemented from GameObject.
createInstance()
Instance & CoreObject::createInstance () inline
Creates and returns a new instance for instanced rendering.
Returns
(Instance&) Reference to the newly created instance.
Definition at line 511 of file object.h.
{
        instances.emplace_back();
        Instance &inst = instances.back();
        inst.position = this->position;
        inst.rotation = this->rotation;
        inst.scale = this->scale;
        inst.updateModelMatrix();
        return inst;
    }
References instances, Instance::position, Instance::rotation, Instance::scale, and Instance::updateModelMatrix().
disableDeferredRendering()
void CoreObject::disableDeferredRendering () inline
Switches the object to forward rendering by binding default shaders.
Definition at line 500 of file object.h.
{
        useDeferredRendering = false;
        this->shaderProgram = ShaderProgram::fromDefaultShaders(
            AtlasVertexShader::Main, AtlasFragmentShader::Main);
    }
References ShaderProgram::fromDefaultShaders(), Main, and useDeferredRendering.
getPipeline()
std::optional< std::shared_ptr< opal::Pipeline > > CoreObject::getPipeline () override virtual
Reimplemented from Renderable.
getPosition()
Position3d CoreObject::getPosition () const inline override virtual
Gets the world-space position of the object.
Reimplemented from Renderable.
Definition at line 572 of file object.h.
{ return position; }
References position.
getRotation()
Rotation3d CoreObject::getRotation () const inline override virtual
Reimplemented from GameObject.
Definition at line 588 of file object.h.
{ return rotation; }
References rotation.
getScale()
Size3d CoreObject::getScale () const inline override virtual
Gets the current non-uniform scale applied to the object.
Reimplemented from Renderable.
Definition at line 582 of file object.h.
{ return scale; }
References scale.
getVertices()
std::vector< CoreVertex > CoreObject::getVertices () const inline override virtual
Returns a copy of the object's vertex collection.
Reimplemented from Renderable.
Definition at line 577 of file object.h.
{ return vertices; }
References vertices.
hide()
void CoreObject::hide () inline override virtual
Hides the object, making it invisible in the scene.
Reimplemented from GameObject.
Definition at line 445 of file object.h.
{ isVisible = false; }
initialize()
void CoreObject::initialize () override virtual
Performs deferred setup of buffers, shaders, and state.
Reimplemented from Renderable.
lookAt()
void CoreObject::lookAt (const Position3d & target, const Normal3d & up = {0.0, 1.0, 0.0}) override virtual
Rotates the object so its forward vector points towards a target.
Reimplemented from GameObject.
makeEmissive()
void CoreObject::makeEmissive (Scene * scene, Color emissionColor, float intensity)
Makes the object emissive by attaching a light to it.
Parameters
scene The scene to add the light to.
emissionColor The color of the emitted light.
intensity The intensity of the emitted light.
move()
void CoreObject::move (const Position3d & deltaPosition) override virtual
Moves the object relative to its current position.
Reimplemented from GameObject.
onCollisionEnter()
void CoreObject::onCollisionEnter (GameObject * other) inline override virtual
Reimplemented from GameObject.
Definition at line 602 of file object.h.
{
        for (auto &component : components) {
            component->onCollisionEnter(other);
        }
    }
References GameObject::components, and GameObject::GameObject().
onCollisionExit()
void CoreObject::onCollisionExit (GameObject * other) inline override virtual
Reimplemented from GameObject.
Definition at line 608 of file object.h.
{
        for (auto &component : components) {
            component->onCollisionExit(other);
        }
    }
References GameObject::components, and GameObject::GameObject().
onCollisionStay()
void CoreObject::onCollisionStay (GameObject * other) inline override virtual
Reimplemented from GameObject.
Definition at line 614 of file object.h.
{
        for (auto &component : components) {
            component->onCollisionStay(other);
        }
    }
References GameObject::components, and GameObject::GameObject().
onQueryReceive()
void CoreObject::onQueryReceive (QueryResult & result) inline override virtual
Reimplemented from GameObject.
Definition at line 640 of file object.h.
{
        for (auto &component : components) {
            component->onQueryReceive(result);
        }
    }
References GameObject::components.
onSignalEnd()
void CoreObject::onSignalEnd (const std::string & signal, GameObject * sender) inline override virtual
Reimplemented from GameObject.
Definition at line 627 of file object.h.
{
        for (auto &component : components) {
            component->onSignalEnd(signal, sender);
        }
    }
References GameObject::components, and GameObject::GameObject().
onSignalRecieve()
void CoreObject::onSignalRecieve (const std::string & signal, GameObject * sender) inline override virtual
Reimplemented from GameObject.
Definition at line 620 of file object.h.
{
        for (auto &component : components) {
            component->onSignalRecieve(signal, sender);
        }
    }
References GameObject::components, and GameObject::GameObject().
refreshPipeline()
void CoreObject::refreshPipeline ()
render()
void CoreObject::render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline = false) override virtual
Draws the object for the current frame.
Parameters
dt Time delta provided by the window loop.
Implements Renderable.
renderColorWithTexture()
void CoreObject::renderColorWithTexture ()
Function to render the object with color and texture.
renderOnlyColor()
void CoreObject::renderOnlyColor ()
Function to render the object with only its color.
renderOnlyTexture()
void CoreObject::renderOnlyTexture ()
Function to render the object with only its texture.
rotate()
void CoreObject::rotate (const Rotation3d & deltaRotation) override virtual
Applies an incremental rotation around the object's axes.
Reimplemented from GameObject.
setColor()
void CoreObject::setColor (const Color & color) override virtual
Sets a solid color override that multiplies with textures.
Reimplemented from GameObject.
setPipeline()
void CoreObject::setPipeline (std::shared_ptr< opal::Pipeline > & pipeline) override virtual
Reimplemented from Renderable.
References pipeline.
setPosition()
void CoreObject::setPosition (const Position3d & newPosition) override virtual
Places the object at an absolute position in world space.
Reimplemented from GameObject.
setProjectionMatrix()
void CoreObject::setProjectionMatrix (const glm::mat4 & projection) override virtual
Uploads the projection matrix that maps camera space to clip space.
Reimplemented from Renderable.
setRotation()
void CoreObject::setRotation (const Rotation3d & newRotation) override virtual
Assigns an absolute rotation to the object.
Reimplemented from GameObject.
setRotationQuat()
void CoreObject::setRotationQuat (const glm::quat & quat)
setScale()
void CoreObject::setScale (const Scale3d & newScale) override virtual
Uniformly scales the object along each axis.
Reimplemented from GameObject.
setViewMatrix()
void CoreObject::setViewMatrix (const glm::mat4 & view) override virtual
Uploads the active view matrix used for transforming vertices to camera space.
Reimplemented from Renderable.
show()
void CoreObject::show () inline override virtual
Shows the object, making it visible in the scene.
Reimplemented from GameObject.
Definition at line 444 of file object.h.
{ isVisible = true; }
update()
void CoreObject::update (Window & window) override virtual
Performs per-frame updates such as component ticking or buffering synchronization.
Reimplemented from Renderable.
References Window.
updateModelMatrix()
void CoreObject::updateModelMatrix ()
Function that updates the model matrix based on the object's position, rotation, and scale.
updateVertices()
void CoreObject::updateVertices ()
Function that updates the object's vertex buffer.
Friends And Related Symbol Documentation
RenderTarget
friend class RenderTarget friend
Definition at line 545 of file object.h.
References RenderTarget.
Skybox
friend class Skybox friend
Definition at line 546 of file object.h.
References Skybox.
Window
friend class Window friend
Definition at line 544 of file object.h.
References Window.
Member Data Documentation
castsShadows
bool CoreObject::castsShadows = true
Variable that determines if the object casts shadows.
Definition at line 458 of file object.h.
indices
std::vector<Index> CoreObject::indices
The indices of the object. These indicate how the vertices are connected to form faces.
Definition at line 287 of file object.h.
instances
std::vector<Instance> CoreObject::instances
Vector of instances for instanced rendering. Multiple copies of the object can be rendered with different transforms efficiently.
Definition at line 305 of file object.h.
light
std::shared_ptr<Light> CoreObject::light = nullptr
The light attached to this object if it's emissive. Used for emissive objects created with makeEmissive().
Definition at line 452 of file object.h.
material
Material CoreObject::material = Material()
The material properties of the object.
Definition at line 298 of file object.h.
pipeline
std::shared_ptr<opal::Pipeline> CoreObject::pipeline
Definition at line 313 of file object.h.
position
Position3d CoreObject::position = {0.0, 0.0, 0.0}
The position of the object in 3D space.
Definition at line 385 of file object.h.
{0.0, 0.0, 0.0};
rotation
Rotation3d CoreObject::rotation = {0.0, 0.0, 0.0}
The rotation of the object in 3D space.
Definition at line 390 of file object.h.
{0.0, 0.0, 0.0};
scale
Scale3d CoreObject::scale = {1.0, 1.0, 1.0}
The scale of the object in 3D space.
Definition at line 395 of file object.h.
{1.0, 1.0, 1.0};
shaderProgram
ShaderProgram CoreObject::shaderProgram
Definition at line 288 of file object.h.
textures
std::vector<Texture> CoreObject::textures
The textures applied to the object.
Definition at line 293 of file object.h.
useDeferredRendering
bool CoreObject::useDeferredRendering = true
Whether the object should use deferred rendering. When false, the object is rendered in the forward rendering pass.
Definition at line 494 of file object.h.
vertices
std::vector<CoreVertex> CoreObject::vertices
The vertices of the object.
Definition at line 281 of file object.h.
The documentation for this class was generated from the following file:
include/atlas/object.h