Atlas: Button Class Reference
Button Class Reference
Clickable push button for Graphite interfaces.
#include <input.h>
Public Types
using ClickCallback
Callback invoked when the button is clicked.
Public Member Functions
Button ()=default
Constructs an empty button.
Button (Font font, std::string label, Position2d position={.x=0.0f,.y=0.0f})
Constructs a button with font, label, and position.
void initialize () override
Prepares the button renderers and label state.
void render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline=false) override
Draws the button and dispatches click interaction.
Size2d getSize () const override
Returns the current rendered size of the button.
Position2d getScreenPosition () const override
Returns the button screen position.
void setScreenPosition (const Position2d &newPosition) override
Sets the button screen position.
const std::string & getLabel () const
Returns the current label.
bool isHovered () const
Returns whether the cursor is currently hovering the button.
bool isEnabled () const
Returns whether the button is enabled.
graphite::UIStyle & style ()
Returns a mutable local style override for this button.
Button & setLabel (std::string newLabel)
Replaces the label text.
Button & setPadding (Size2d newPadding)
Replaces the inner padding.
Button & setMinimumSize (Size2d newMinimumSize)
Replaces the minimum button size.
Button & setFontSize (float newFontSize)
Replaces the explicit font size override.
Button & setStyle (const graphite::UIStyle &newStyle)
Replaces the local style override.
Button & setOnClick (ClickCallback callback)
Registers the callback invoked when the button is clicked.
Button & setEnabled (bool newEnabled)
Enables or disables interaction.
Public Member Functions inherited from GameObject
GameObject ()
Construct a new GameObject and assign it a unique ID.
GameObject (const GameObject &other)
GameObject (GameObject &&other) noexcept
GameObject & operator= (const GameObject &other)
GameObject & operator= (GameObject &&other) noexcept
virtual ~GameObject ()
virtual void attachProgram (const ShaderProgram &program)
Attaches a shader program to the object.
virtual void createAndAttachProgram (VertexShader &vertexShader, FragmentShader &fragmentShader)
Creates and attaches a shader program to the object.
virtual void attachTexture (const Texture &texture)
Attaches a texture to the object.
virtual void setColor (const Color &color)
Sets the color of the object.
virtual void setPosition (const Position3d &newPosition)
Sets the position of the object.
virtual void move (const Position3d &deltaPosition)
Moves the object by a certain amount.
virtual void setRotation (const Rotation3d &newRotation)
Sets the rotation of the object.
virtual void lookAt (const Position3d &target, const Normal3d &up)
Sets the object to look at a specific point in 3D space.
virtual void rotate (const Rotation3d &deltaRotation)
Rotates the object by a certain amount.
virtual void setScale (const Scale3d &newScale)
Sets the scale of the object.
virtual void hide ()
Hides the object, making it invisible in the scene.
virtual void show ()
Shows the object, making it visible in the scene.
virtual void onCollisionEnter (GameObject *other)
virtual void onCollisionExit (GameObject *other)
virtual void onCollisionStay (GameObject *other)
virtual void onSignalRecieve (const std::string &signal, GameObject *sender)
virtual void onSignalEnd (const std::string &signal, GameObject *sender)
virtual void onQueryReceive (QueryResult &result)
template<typename T>
void addComponent (T &&existing)
Adds a component to the object.
void beforePhysics () override
template<typename U, typename T>
void addTraitComponent (T &&existing)
Adds a trait component to the object. A trait component is a component that is tied to a specific type of GameObject.
template<typename T>
std::shared_ptr< T > getComponent ()
Gets the first component that matches the specified type.
unsigned int getId () override
Returns the unique identifier associated with this object.
virtual Rotation3d getRotation () const
Returns object rotation in Euler angles.
void addDependency (GameObject *obj)
Adds another object as a dependency for update ordering.
std::vector< GameObject * > getDependencies () const
Returns all registered dependencies for this object.
Public Member Functions inherited from Renderable
virtual void update (Window &window)
Function to update the object each frame.
virtual void setViewMatrix (const glm::mat4 &view)
Function to set the view matrix for the object. Called from Window for internal purposes.
virtual void setProjectionMatrix (const glm::mat4 &projection)
Function to set the projection matrix for the object. Called from Window for internal purposes.
virtual std::optional< std::shared_ptr< opal::Pipeline > > getPipeline ()
virtual void setPipeline (std::shared_ptr< opal::Pipeline > &pipeline)
virtual std::optional< ShaderProgram > getShaderProgram ()
Returns the currently bound shader program, if any.
virtual void setShader (const ShaderProgram &shaderProgram)
Replaces the shader program bound to the renderable.
virtual Position3d getPosition () const
Function to get the position of the object in 3D space.
virtual std::vector< CoreVertex > getVertices () const
Function to get the vertices of the object in 3D space.
virtual Size3d getScale () const
Function to get the scale of the object in 3D space.
virtual bool canCastShadows () const
Function to determine if the object can cast shadows. Can be overridden by derived classes.
virtual ~Renderable ()=default
Public Attributes
std::string label
Text shown inside the button.
Font font
Font used to render the label.
Position2d position
Screen-space top-left position of the button.
float fontSize = 0.0f
Explicit font size override. Uses the font's native size when 0.
Size2d padding {.width = 18.0f, .height = 12.0f}
Inner padding applied around the label.
Size2d minimumSize {.width = 0.0f, .height = 0.0f}
Minimum size enforced after measuring the label.
Color textColor = Color::white()
Label color.
Color backgroundColor = Color(0.15f, 0.16f, 0.2f, 0.96f)
Default button background.
Color hoverBackgroundColor = Color(0.2f, 0.22f, 0.27f, 0.98f)
Background used while the cursor hovers the button.
Color pressedBackgroundColor = Color(1.0f, 0.55f, 0.14f, 0.96f)
Background used while the button is pressed.
Color borderColor = Color(1.0f, 1.0f, 1.0f, 0.16f)
Border color used while idle.
Color hoverBorderColor = Color(1.0f, 0.55f, 0.14f, 1.0f)
Border color used while hovered.
bool enabled = true
Whether the button can currently be interacted with.
Public Attributes inherited from GameObject
Rigidbody * rigidbody = nullptr
Cached rigidbody component pointer when attached.
Public Attributes inherited from Renderable
bool renderDepthOfView = false
Whether the object should be included in depth of field calculations. When true, contributes to blur effects.
bool renderLateForward = false
Whether the object must be moved to the late forward rendering pipeline. Objects flagged here are skipped during the primary forward pass and rendered only after all standard forward elements.
Additional Inherited Members
Protected Attributes inherited from GameObject
std::vector< std::shared_ptr< Component > > components
std::vector< GameObject * > dependencies
int id
The unique identifier for the object.
Detailed Description
Clickable push button for Graphite interfaces.
Example
Button saveButton(Font::getFont("Inter"), "Save", {.x = 24.0f, .y = 72.0f});
saveButton.setOnClick([](const ButtonClickEvent &event) {
    std::cout << "Clicked: " << event.label << '\n';
});
saveButton.style().hovered().background(Color(0.22f, 0.24f, 0.3f, 1.0f));
Definition at line 180 of file input.h.
Member Typedef Documentation
ClickCallback
using Button::ClickCallback
Initial value:
std::function<void(const ButtonClickEvent &)>
Callback invoked when the button is clicked.
Definition at line 183 of file input.h.
Constructor & Destructor Documentation
Button() [1/2]
Button::Button () default
Constructs an empty button.
Button() [2/2]
Button::Button (Font font, std::string label, Position2d position = {.x=0.0f,.y=0.0f})
Constructs a button with font, label, and position.
References font, label, and position.
Member Function Documentation
getLabel()
const std::string & Button::getLabel () const inline
Returns the current label.
Definition at line 236 of file input.h.
{ return label; }
References label.
getScreenPosition()
Position2d Button::getScreenPosition () const inline override virtual
Returns the button screen position.
Reimplemented from UIObject.
Definition at line 229 of file input.h.
{ return position; }
References position.
getSize()
Size2d Button::getSize () const override virtual
Returns the current rendered size of the button.
Reimplemented from UIObject.
initialize()
void Button::initialize () override virtual
Prepares the button renderers and label state.
Reimplemented from Renderable.
isEnabled()
bool Button::isEnabled () const inline
Returns whether the button is enabled.
Definition at line 240 of file input.h.
{ return enabled; }
References enabled.
isHovered()
bool Button::isHovered () const inline
Returns whether the cursor is currently hovering the button.
Definition at line 238 of file input.h.
{ return hovered; }
render()
void Button::render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline = false) override virtual
Draws the button and dispatches click interaction.
Implements Renderable.
setEnabled()
Button & Button::setEnabled (bool newEnabled)
Enables or disables interaction.
References Button(), and style().
setFontSize()
Button & Button::setFontSize (float newFontSize)
Replaces the explicit font size override.
References Button().
setLabel()
Button & Button::setLabel (std::string newLabel)
Replaces the label text.
References Button().
setMinimumSize()
Button & Button::setMinimumSize (Size2d newMinimumSize)
Replaces the minimum button size.
References Button().
setOnClick()
Button & Button::setOnClick (ClickCallback callback)
Registers the callback invoked when the button is clicked.
References Button().
setPadding()
Button & Button::setPadding (Size2d newPadding)
Replaces the inner padding.
References Button().
setScreenPosition()
void Button::setScreenPosition (const Position2d & newPosition) inline override virtual
Sets the button screen position.
Implements UIObject.
Definition at line 231 of file input.h.
{
        position = newPosition;
    }
References position.
setStyle()
Button & Button::setStyle (const graphite::UIStyle & newStyle)
Replaces the local style override.
References Button().
style()
graphite::UIStyle & Button::style () inline
Returns a mutable local style override for this button.
Definition at line 242 of file input.h.
{
        usesLocalStyle = true;
        return localStyle;
    }
Member Data Documentation
backgroundColor
Color Button::backgroundColor = Color(0.15f, 0.16f, 0.2f, 0.96f)
Default button background.
Definition at line 201 of file input.h.
borderColor
Color Button::borderColor = Color(1.0f, 1.0f, 1.0f, 0.16f)
Border color used while idle.
Definition at line 207 of file input.h.
enabled
bool Button::enabled = true
Whether the button can currently be interacted with.
Definition at line 211 of file input.h.
font
Font Button::font
Font used to render the label.
Definition at line 189 of file input.h.
fontSize
float Button::fontSize = 0.0f
Explicit font size override. Uses the font's native size when 0.
Definition at line 193 of file input.h.
hoverBackgroundColor
Color Button::hoverBackgroundColor = Color(0.2f, 0.22f, 0.27f, 0.98f)
Background used while the cursor hovers the button.
Definition at line 203 of file input.h.
hoverBorderColor
Color Button::hoverBorderColor = Color(1.0f, 0.55f, 0.14f, 1.0f)
Border color used while hovered.
Definition at line 209 of file input.h.
label
std::string Button::label
Text shown inside the button.
Definition at line 187 of file input.h.
minimumSize
Size2d Button::minimumSize {.width = 0.0f, .height = 0.0f}
Minimum size enforced after measuring the label.
Definition at line 197 of file input.h.
{.width = 0.0f, .height = 0.0f};
padding
Size2d Button::padding {.width = 18.0f, .height = 12.0f}
Inner padding applied around the label.
Definition at line 195 of file input.h.
{.width = 18.0f, .height = 12.0f};
position
Position2d Button::position
Screen-space top-left position of the button.
Definition at line 191 of file input.h.
pressedBackgroundColor
Color Button::pressedBackgroundColor = Color(1.0f, 0.55f, 0.14f, 0.96f)
Background used while the button is pressed.
Definition at line 205 of file input.h.
textColor
Color Button::textColor = Color::white()
Label color.
Definition at line 199 of file input.h.
The documentation for this class was generated from the following file:
include/graphite/input.h