Atlas: Bounds Class Reference
Bounds Class Reference
Class representing an axis-aligned bounding box (AABB) used for collision detection. Provides methods for intersection testing and expansion operations.
#include <bounds.h>
Public Member Functions
Bounds ()
Default constructor for Bounds.
Bounds (const Bounds &rhs)
Copy constructor for Bounds.
const Bounds & operator= (const Bounds &rhs)
Assignment operator for Bounds.
~Bounds ()=default
void clear ()
Clears the bounds, resetting them to default values.
bool doesIntersect (const Bounds &other)
Checks if this bounds intersects with another bounds.
void expand (std::vector< glm::vec3 > pts, const int number)
Expands the bounds to include a set of points.
void expand (const glm::vec3 rhs)
Expands the bounds to include a single point.
void expand (const Bounds &rhs)
Expands the bounds to include another bounds.
float widthX () const
Gets the width of the bounds along the X-axis.
float widthY () const
Gets the width of the bounds along the Y-axis.
float widthZ () const
Gets the width of the bounds along the Z-axis.
Public Attributes
glm::vec3 mins
glm::vec3 maxs
Detailed Description
Class representing an axis-aligned bounding box (AABB) used for collision detection. Provides methods for intersection testing and expansion operations.
Example
// Create and expand bounds for a mesh
Bounds objectBounds;
objectBounds.expand(glm::vec3(-5.0f, 0.0f, -5.0f));
objectBounds.expand(glm::vec3(5.0f, 10.0f, 5.0f));
// Test intersection with another object
Bounds otherBounds;
otherBounds.expand(glm::vec3(3.0f, 0.0f, 3.0f));
otherBounds.expand(glm::vec3(8.0f, 5.0f, 8.0f));
if (objectBounds.doesIntersect(otherBounds)) {
    // Handle collision
}
// Get bounds dimensions
float width = objectBounds.widthX();
float height = objectBounds.widthY();
float depth = objectBounds.widthZ();
// Broad-phase collision detection for physics simulation
std::vector<std::shared_ptr<Body>> bodies = {...};
std::vector<CollisionPair> collisionPairs;
bezel::broadPhase(bodies, collisionPairs, deltaTime);
// Process potential collisions
for (const auto& pair : collisionPairs) {
    // Perform narrow-phase collision detection on pair.a and pair.b
}
Definition at line 55 of file bounds.h.
Constructor & Destructor Documentation
Bounds() [1/2]
Bounds::Bounds ()
Default constructor for Bounds.
Bounds() [2/2]
Bounds::Bounds (const Bounds & rhs) inline
Copy constructor for Bounds.
Parameters
rhs The Bounds object to copy from.
Definition at line 67 of file bounds.h.
: mins(rhs.mins), maxs(rhs.maxs) {}
References Bounds(), maxs, and mins.
~Bounds()
Bounds::~Bounds () default
Member Function Documentation
clear()
void Bounds::clear ()
Clears the bounds, resetting them to default values.
doesIntersect()
bool Bounds::doesIntersect (const Bounds & other)
Checks if this bounds intersects with another bounds.
Parameters
other The other bounds to check intersection with.
Returns
(bool) True if the bounds intersect, false otherwise.
References Bounds().
expand() [1/3]
void Bounds::expand (const Bounds & rhs)
Expands the bounds to include another bounds.
Parameters
rhs The bounds to include.
References Bounds().
expand() [2/3]
void Bounds::expand (const glm::vec3 rhs)
Expands the bounds to include a single point.
Parameters
rhs The point to include in the bounds.
expand() [3/3]
void Bounds::expand (std::vector< glm::vec3 > pts, const int number)
Expands the bounds to include a set of points.
Parameters
pts The vector of points to include.
number The number of points to process.
operator=()
const Bounds & Bounds::operator= (const Bounds & rhs)
Assignment operator for Bounds.
Parameters
rhs The Bounds object to assign from.
Returns
(const Bounds&) Reference to this Bounds object.
References Bounds().
widthX()
float Bounds::widthX () const inline
Gets the width of the bounds along the X-axis.
Returns
(float) The width in the X dimension.
Definition at line 114 of file bounds.h.
{ return maxs.x - mins.x; }
References maxs, and mins.
widthY()
float Bounds::widthY () const inline
Gets the width of the bounds along the Y-axis.
Returns
(float) The width in the Y dimension.
Definition at line 120 of file bounds.h.
{ return maxs.y - mins.y; }
References maxs, and mins.
widthZ()
float Bounds::widthZ () const inline
Gets the width of the bounds along the Z-axis.
Returns
(float) The width in the Z dimension.
Definition at line 126 of file bounds.h.
{ return maxs.z - mins.z; }
References maxs, and mins.
Member Data Documentation
maxs
glm::vec3 Bounds::maxs
Definition at line 129 of file bounds.h.
mins
glm::vec3 Bounds::mins
Definition at line 128 of file bounds.h.
The documentation for this class was generated from the following file:
include/bezel/native/bounds.h