Atlas: Workspace Class Reference
Workspace Class Reference
Singleton class that manages all resources and resource groups in the application. Provides centralized access to assets like images, audio files, and other resources.
#include <workspace.h>
Public Member Functions
Workspace (const Workspace &)=delete
Workspace & operator= (const Workspace &)=delete
Resource createResource (const fs::path &path, std::string name, ResourceType type=ResourceType::File)
Creates a new resource from a file path.
ResourceGroup createResourceGroup (std::string groupName, const std::vector< Resource > &resources)
Creates a new resource group containing multiple resources.
Resource getResource (std::string name)
Retrieves a resource by its name.
std::vector< Resource > getAllResources ()
Gets all resources registered in the workspace.
std::vector< Resource > getResourcesByType (ResourceType type)
Gets all resources of a specific type.
ResourceGroup getResourceGroup (std::string groupName)
Retrieves a resource group by its name.
std::vector< ResourceGroup > getAllResourceGroups ()
Gets all resource groups registered in the workspace.
void setRootPath (const fs::path &path)
Sets the root path for the workspace.
Static Public Member Functions
static Workspace & get ()
Detailed Description
Singleton class that manages all resources and resource groups in the application. Provides centralized access to assets like images, audio files, and other resources.
Example
// Get the workspace instance
Workspace &workspace = Workspace::get();
// Set the root path for resources
workspace.setRootPath("assets/");
// Create a resource
Resource texture = workspace.createResource("textures/brick.png",
"BrickTexture", ResourceType::Image);
// Create a resource group
std::vector<Resource> skyboxResources = {...};
ResourceGroup skybox = workspace.createResourceGroup("Skybox",
skyboxResources);
Definition at line 89 of file workspace.h.
Constructor & Destructor Documentation
Workspace()
Workspace::Workspace (const Workspace &) delete
References Workspace().
Member Function Documentation
createResource()
Resource Workspace::createResource (const fs::path & path, std::string name, ResourceType type = ResourceType::File)
Creates a new resource from a file path.
Parameters
path The filesystem path to the resource.
name The name to assign to the resource.
type The type of resource to create.
Returns
(Resource) The created resource.
References File.
createResourceGroup()
ResourceGroup Workspace::createResourceGroup (std::string groupName, const std::vector< Resource > & resources)
Creates a new resource group containing multiple resources.
Parameters
groupName The name for the resource group.
resources The vector of resources to include in the group.
Returns
(ResourceGroup) The created resource group.
get()
Workspace & Workspace::get () inline static
Definition at line 91 of file workspace.h.
{
        static Workspace instance;
        return instance;
    }
References Workspace().
getAllResourceGroups()
std::vector< ResourceGroup > Workspace::getAllResourceGroups ()
Gets all resource groups registered in the workspace.
Returns
(std::vector<ResourceGroup>) Vector containing all resource groups.
getAllResources()
std::vector< Resource > Workspace::getAllResources ()
Gets all resources registered in the workspace.
Returns
(std::vector<Resource>) Vector containing all resources.
getResource()
Resource Workspace::getResource (std::string name)
Retrieves a resource by its name.
Parameters
name The name of the resource to retrieve.
Returns
(Resource) The found resource.
getResourceGroup()
ResourceGroup Workspace::getResourceGroup (std::string groupName)
Retrieves a resource group by its name.
Parameters
groupName The name of the resource group to retrieve.
Returns
(ResourceGroup) The found resource group.
getResourcesByType()
std::vector< Resource > Workspace::getResourcesByType (ResourceType type)
Gets all resources of a specific type.
Parameters
type The type of resources to retrieve.
Returns
(std::vector<Resource>) Vector containing resources of the specified type.
operator=()
Workspace & Workspace::operator= (const Workspace &) delete
References Workspace().
setRootPath()
void Workspace::setRootPath (const fs::path & path) inline
Sets the root path for the workspace.
Parameters
path The root filesystem path to set.
Definition at line 160 of file workspace.h.
{ rootPath = path; }
The documentation for this class was generated from the following file:
include/atlas/workspace.h