Atlas: Row Class Reference
Row Class Reference
Horizontal layout that arranges children from left to right.
#include <layout.h>
Public Member Functions
Row (Position2d pos={.x=0,.y=0})
Constructs an empty row at the given position.
Row (const std::vector< UIObject * > &children, float spacing=0.0f, Size2d padding={.width=0.0f,.height=0.0f}, Position2d pos={.x=0,.y=0})
Constructs a row with children, spacing, padding, and position.
void render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline) override
Renders the row background and all children.
void setViewMatrix (const glm::mat4 &view) override
Propagates the view matrix to all children.
void setProjectionMatrix (const glm::mat4 &projection) override
Propagates the projection matrix to all children.
void addChild (UIObject *child)
Appends a child to the layout.
void setChildren (const std::vector< UIObject * > &newChildren)
Replaces the child list for the layout.
Size2d getSize () const override
Computes the layout size including padding and child spacing.
Position2d getScreenPosition () const override
Returns the layout screen position.
void setScreenPosition (const Position2d &newPosition) override
Sets the layout screen position and recomputes child placement.
graphite::UIStyle & style ()
Returns a mutable local style override for this layout.
Row & setStyle (const graphite::UIStyle &newStyle)
Replaces the local style override for this layout.
Public Member Functions inherited from GameObject
GameObject ()
Construct a new GameObject and assign it a unique ID.
GameObject (const GameObject &other)
GameObject (GameObject &&other) noexcept
GameObject & operator= (const GameObject &other)
GameObject & operator= (GameObject &&other) noexcept
virtual ~GameObject ()
virtual void attachProgram (const ShaderProgram &program)
Attaches a shader program to the object.
virtual void createAndAttachProgram (VertexShader &vertexShader, FragmentShader &fragmentShader)
Creates and attaches a shader program to the object.
virtual void attachTexture (const Texture &texture)
Attaches a texture to the object.
virtual void setColor (const Color &color)
Sets the color of the object.
virtual void setPosition (const Position3d &newPosition)
Sets the position of the object.
virtual void move (const Position3d &deltaPosition)
Moves the object by a certain amount.
virtual void setRotation (const Rotation3d &newRotation)
Sets the rotation of the object.
virtual void lookAt (const Position3d &target, const Normal3d &up)
Sets the object to look at a specific point in 3D space.
virtual void rotate (const Rotation3d &deltaRotation)
Rotates the object by a certain amount.
virtual void setScale (const Scale3d &newScale)
Sets the scale of the object.
virtual void hide ()
Hides the object, making it invisible in the scene.
virtual void show ()
Shows the object, making it visible in the scene.
virtual void onCollisionEnter (GameObject *other)
virtual void onCollisionExit (GameObject *other)
virtual void onCollisionStay (GameObject *other)
virtual void onSignalRecieve (const std::string &signal, GameObject *sender)
virtual void onSignalEnd (const std::string &signal, GameObject *sender)
virtual void onQueryReceive (QueryResult &result)
template<typename T>
void addComponent (T &&existing)
Adds a component to the object.
void beforePhysics () override
template<typename U, typename T>
void addTraitComponent (T &&existing)
Adds a trait component to the object. A trait component is a component that is tied to a specific type of GameObject.
template<typename T>
std::shared_ptr< T > getComponent ()
Gets the first component that matches the specified type.
unsigned int getId () override
Returns the unique identifier associated with this object.
virtual Rotation3d getRotation () const
Returns object rotation in Euler angles.
void addDependency (GameObject *obj)
Adds another object as a dependency for update ordering.
std::vector< GameObject * > getDependencies () const
Returns all registered dependencies for this object.
Public Member Functions inherited from Renderable
virtual void initialize ()
Function to initialize the object. Can be overridden by derived.
virtual void update (Window &window)
Function to update the object each frame.
virtual std::optional< std::shared_ptr< opal::Pipeline > > getPipeline ()
virtual void setPipeline (std::shared_ptr< opal::Pipeline > &pipeline)
virtual std::optional< ShaderProgram > getShaderProgram ()
Returns the currently bound shader program, if any.
virtual void setShader (const ShaderProgram &shaderProgram)
Replaces the shader program bound to the renderable.
virtual Position3d getPosition () const
Function to get the position of the object in 3D space.
virtual std::vector< CoreVertex > getVertices () const
Function to get the vertices of the object in 3D space.
virtual Size3d getScale () const
Function to get the scale of the object in 3D space.
virtual bool canCastShadows () const
Function to determine if the object can cast shadows. Can be overridden by derived classes.
virtual ~Renderable ()=default
Public Attributes
float spacing = 0.0f
Spacing inserted between consecutive children.
Size2d maxSize {.width = 0.0f, .height = 0.0f}
Minimum size enforced for the layout container.
Size2d padding {.width = 0.0f, .height = 0.0f}
Padding applied around the children.
std::vector< UIObject * > children
Child elements owned externally by the caller.
Position2d position
Screen-space anchor position of the layout container.
ElementAlignment alignment = ElementAlignment::Center
Vertical alignment applied to each child within the row.
LayoutAnchor anchor = LayoutAnchor::TopLeft
Anchor mode used to interpret position.
Public Attributes inherited from GameObject
Rigidbody * rigidbody = nullptr
Cached rigidbody component pointer when attached.
Public Attributes inherited from Renderable
bool renderDepthOfView = false
Whether the object should be included in depth of field calculations. When true, contributes to blur effects.
bool renderLateForward = false
Whether the object must be moved to the late forward rendering pipeline. Objects flagged here are skipped during the primary forward pass and rendered only after all standard forward elements.
Additional Inherited Members
Protected Attributes inherited from GameObject
std::vector< std::shared_ptr< Component > > components
std::vector< GameObject * > dependencies
int id
The unique identifier for the object.
Detailed Description
Horizontal layout that arranges children from left to right.
Example
Checkbox music(Font::getFont("Inter"), "Music", true);
Checkbox sfx(Font::getFont("Inter"), "SFX", true);
Row toggles({&music, &sfx}, 16.0f, {.width = 12.0f, .height = 12.0f},
            {.x = 24.0f, .y = 96.0f});
toggles.alignment = ElementAlignment::Center;
Definition at line 198 of file layout.h.
Constructor & Destructor Documentation
Row() [1/2]
Row::Row (Position2d pos = {.x = 0, .y = 0}) inline
Constructs an empty row at the given position.
Definition at line 201 of file layout.h.
                       {.x = 0, .y = 0}) : position(pos) {
        recalculatePositions();
    }
Row() [2/2]
Row::Row (const std::vector< UIObject * > & children, float spacing = 0.0f, Size2d padding = {.width = 0.0f, .height = 0.0f}, Position2d pos = {.x = 0, .y = 0}) inline
Constructs a row with children, spacing, padding, and position.
Definition at line 206 of file layout.h.
                       {.width = 0.0f, .height = 0.0f},
        Position2d pos = {.x = 0, .y = 0})
        : spacing(spacing), padding(padding), children(children),
          position(pos) {
        recalculatePositions();
    }
References children, padding, and spacing.
Member Function Documentation
addChild()
void Row::addChild (UIObject * child)
Appends a child to the layout.
getScreenPosition()
Position2d Row::getScreenPosition () const inline override virtual
Returns the layout screen position.
Reimplemented from UIObject.
Definition at line 276 of file layout.h.
{ return position; }
References position.
getSize()
Size2d Row::getSize () const inline override virtual
Computes the layout size including padding and child spacing.
Reimplemented from UIObject.
Definition at line 244 of file layout.h.
{
        graphite::UIStyle fallbackStyle;
        fallbackStyle.normal().padding(padding);
        const graphite::UIResolvedStyle style = graphite::resolveStyle(
            fallbackStyle, &graphite::Theme::current().row,
            usesLocalStyle ? &localStyle : nullptr);
        const Size2d effectivePadding = style.padding;
        float totalWidth = effectivePadding.width * 2.0f;
        float maxHeight = 0.0f;
        bool hasChild = false;
        for (const auto *child : children) {
            if (child == nullptr) {
                continue;
            }
            Size2d childSize = child->getSize();
            if (hasChild) {
                totalWidth += spacing;
            }
            totalWidth += childSize.width;
            maxHeight = std::max(maxHeight, childSize.height);
            hasChild = true;
        }
        return Size2d{
            .width = std::max(totalWidth, maxSize.width),
            .height = std::max(maxHeight + (effectivePadding.height * 2.0f),
                               maxSize.height),
        };
    }
References children, graphite::Theme::current(), Size2d::height, maxSize, graphite::UIStyle::normal(), graphite::UIStyleVariant::padding(), padding, graphite::resolveStyle(), spacing, style(), and Size2d::width.
render()
void Row::render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline) override virtual
Renders the row background and all children.
Implements Renderable.
setChildren()
void Row::setChildren (const std::vector< UIObject * > & newChildren)
Replaces the child list for the layout.
setProjectionMatrix()
void Row::setProjectionMatrix (const glm::mat4 & projection) override virtual
Propagates the projection matrix to all children.
Reimplemented from Renderable.
setScreenPosition()
void Row::setScreenPosition (const Position2d & newPosition) inline override virtual
Sets the layout screen position and recomputes child placement.
Implements UIObject.
Definition at line 279 of file layout.h.
{
        position = newPosition;
        recalculatePositions();
    }
References position.
setStyle()
Row & Row::setStyle (const graphite::UIStyle & newStyle) inline
Replaces the local style override for this layout.
Definition at line 291 of file layout.h.
{
        localStyle = newStyle;
        usesLocalStyle = true;
        recalculatePositions();
        return *this;
    }
References Row().
setViewMatrix()
void Row::setViewMatrix (const glm::mat4 & view) override virtual
Propagates the view matrix to all children.
Reimplemented from Renderable.
style()
graphite::UIStyle & Row::style () inline
Returns a mutable local style override for this layout.
Definition at line 285 of file layout.h.
{
        usesLocalStyle = true;
        return localStyle;
    }
Member Data Documentation
alignment
ElementAlignment Row::alignment = ElementAlignment::Center
Vertical alignment applied to each child within the row.
Definition at line 229 of file layout.h.
anchor
LayoutAnchor Row::anchor = LayoutAnchor::TopLeft
Anchor mode used to interpret position.
Definition at line 231 of file layout.h.
children
std::vector<UIObject *> Row::children
Child elements owned externally by the caller.
Definition at line 225 of file layout.h.
maxSize
Size2d Row::maxSize {.width = 0.0f, .height = 0.0f}
Minimum size enforced for the layout container.
Definition at line 221 of file layout.h.
{.width = 0.0f, .height = 0.0f};
padding
Size2d Row::padding {.width = 0.0f, .height = 0.0f}
Padding applied around the children.
Definition at line 223 of file layout.h.
{.width = 0.0f, .height = 0.0f};
position
Position2d Row::position
Screen-space anchor position of the layout container.
Definition at line 227 of file layout.h.
spacing
float Row::spacing = 0.0f
Spacing inserted between consecutive children.
Definition at line 219 of file layout.h.
The documentation for this class was generated from the following file:
include/graphite/layout.h