Atlas: AudioPlayer Class Reference
AudioPlayer Class Reference
Component that provides audio playback capabilities to an object. It can be attach to any object in the scene and allows for playing, pausing and stopping audio.
#include <audio.h>
Public Member Functions
AudioPlayer ()
Construct a new empty AudioPlayer object.
AudioPlayer (const AudioPlayer &)=delete
Destroy the Audio Player object and release resources.
AudioPlayer & operator= (const AudioPlayer &)=delete
Destroy the Audio Player object and release resources.
AudioPlayer (AudioPlayer &&other) noexcept
Move constructor for AudioPlayer.
AudioPlayer & operator= (AudioPlayer &&other) noexcept
Move assignment operator for AudioPlayer.
void init () override
Initialize the audio player and prepare it for playback.
void play ()
Play the audio from the beginning or resume if paused.
void pause ()
Pause the audio playback. It can be resumed later.
void stop ()
Stop the audio playback and reset to the beginning.
void setSource (Resource sourceResource)
Set the source from where the audio will be played.
void update (float dt) override
Update the audio player state. This method is called every frame.
void setPosition (Position3d position)
Set the position of the audio source in 3D space.
void useSpatialization ()
Enable spatialization for the audio source, making it 3D and affected by the listener's position.
void disableSpatialization ()
Disable spatialization for the audio source, making it play uniformly regardless of the listener's position.
Public Member Functions inherited from Component
virtual void setViewMatrix (const glm::mat4 &view)
Performs changes when the GameObject's view matrix is updated.
virtual void setProjectionMatrix (const glm::mat4 &projection)
Performs changes when the GameObject's projection matrix is updated.
Window * getWindow ()
Gets the window associated with the component's GameObject.
Component ()=default
Construct a new Component object.
Public Attributes
std::unique_ptr< AudioSource > source
Get the audio source. This allows for advanced manipulation of the audio playback.
Public Attributes inherited from Component
GameObject * object = nullptr
Gets the GameObject associated with the component.
Body * body = nullptr
Gets the Body associated with the component.
Detailed Description
Component that provides audio playback capabilities to an object. It can be attach to any object in the scene and allows for playing, pausing and stopping audio.
Note
Finewave will be required for this component to work. This component under the hood uses Finewave's AudioSource class to manage audio playback.
Example
// Create an AudioPlayer component
auto audioPlayer = std::make_shared<AudioPlayer>();
// Initialize the audio player
audioPlayer->init();
// Set the audio source from a file
audioPlayer->setSource(Workspace::get().getResource("AudioResource"));
// Play the audio
audioPlayer->play();
Definition at line 42 of file audio.h.
Constructor & Destructor Documentation
AudioPlayer() [1/3]
AudioPlayer::AudioPlayer () inline
Construct a new empty AudioPlayer object.
Definition at line 48 of file audio.h.
: sourceInitialized(false) {}
AudioPlayer() [2/3]
AudioPlayer::AudioPlayer (const AudioPlayer &) delete
Destroy the Audio Player object and release resources.
References AudioPlayer().
AudioPlayer() [3/3]
AudioPlayer::AudioPlayer (AudioPlayer && other) inline noexcept
Move constructor for AudioPlayer.
Parameters
other The AudioPlayer instance to move from.
Definition at line 67 of file audio.h.
        : source(std::move(other.source)),
          sourceInitialized(other.sourceInitialized) {
        other.sourceInitialized = false;
    }
References AudioPlayer().
Member Function Documentation
disableSpatialization()
void AudioPlayer::disableSpatialization () inline
Disable spatialization for the audio source, making it play uniformly regardless of the listener's position.
Definition at line 184 of file audio.h.
{
        ensureSourceInitialized();
        source->disableSpatialization();
    }
References source.
init()
void AudioPlayer::init () inline override virtual
Initialize the audio player and prepare it for playback.
Reimplemented from Component.
Definition at line 92 of file audio.h.
{
        if (!sourceInitialized) {
            source = std::make_unique<AudioSource>();
            sourceInitialized = true;
        }
    }
References source.
operator=() [1/2]
AudioPlayer & AudioPlayer::operator= (AudioPlayer && other) inline noexcept
Move assignment operator for AudioPlayer.
Parameters
other The AudioPlayer instance to move from.
Returns
AudioPlayer& Reference to the current instance after move.
Definition at line 79 of file audio.h.
{
        if (this != &other) {
            source = std::move(other.source);
            sourceInitialized = other.sourceInitialized;
            other.sourceInitialized = false;
        }
        return *this;
    }
References AudioPlayer(), and source.
operator=() [2/2]
AudioPlayer & AudioPlayer::operator= (const AudioPlayer &) delete
Destroy the Audio Player object and release resources.
Returns
AudioPlayer&
References AudioPlayer().
pause()
void AudioPlayer::pause () inline
Pause the audio playback. It can be resumed later.
Definition at line 112 of file audio.h.
{
        ensureSourceInitialized();
        source->pause();
    }
References source.
play()
void AudioPlayer::play () inline
Play the audio from the beginning or resume if paused.
Definition at line 103 of file audio.h.
                       {
        ensureSourceInitialized();
        source->play();
    }
References source.
setPosition()
void AudioPlayer::setPosition (Position3d position) inline
Set the position of the audio source in 3D space.
Warning
This is used when spatialization is on.
Parameters
position The new position of the audio source.
Definition at line 164 of file audio.h.
{
        ensureSourceInitialized();
        source->setPosition(position);
    }
References source.
setSource()
void AudioPlayer::setSource (Resource sourceResource) inline
Set the source from where the audio will be played.
Parameters
sourceResource The resource containing the audio file.
Definition at line 131 of file audio.h.
{
        ensureSourceInitialized();
        source->fromFile(sourceResource);
    }
References source.
stop()
void AudioPlayer::stop () inline
Stop the audio playback and reset to the beginning.
Definition at line 121 of file audio.h.
                       {
        ensureSourceInitialized();
        source->stop();
    }
References source.
update()
void AudioPlayer::update (float dt) inline override virtual
Update the audio player state. This method is called every frame.
Parameters
dt The delta time since the last update.
Reimplemented from Component.
Definition at line 141 of file audio.h.
{
        ensureSourceInitialized();
        Window *window = Window::mainWindow;
        Camera *mainCamera = window->getCamera();
        if (mainCamera) {
            Position3d cameraPos = mainCamera->position;
            Normal3d cameraFront = mainCamera->getFrontVector();
            window->audioEngine->setListenerPosition(cameraPos);
            window->audioEngine->setListenerOrientation(
                cameraFront, Normal3d{0.0f, 1.0f, 0.0f});
            window->audioEngine->setListenerVelocity(mainCamera->getVelocity());
        }
        source->setPosition(this->object->getPosition());
    }
References Window::audioEngine, Window::getCamera(), Camera::getFrontVector(), Camera::getVelocity(), Window::mainWindow, Component::object, Camera::position, and source.
useSpatialization()
void AudioPlayer::useSpatialization () inline
Enable spatialization for the audio source, making it 3D and affected by the listener's position.
Definition at line 174 of file audio.h.
{
        ensureSourceInitialized();
        source->useSpatialization();
    }
References source.
Member Data Documentation
source
std::unique_ptr<AudioSource> AudioPlayer::source
Get the audio source. This allows for advanced manipulation of the audio playback.
Definition at line 194 of file audio.h.
The documentation for this class was generated from the following file:
include/atlas/audio.h