Atlas: TextField Class Reference
TextField Class Reference
Single-line editable text input for Graphite interfaces.
#include <input.h>
Public Types
using ChangeCallback
Callback invoked when text or focus state changes.
Public Member Functions
TextField ()=default
Constructs an empty text field.
TextField (Font font, float maximumWidth, Position2d position={.x=0.0f,.y=0.0f}, std::string text="", std::string placeholder="")
Constructs a text field with font, width, position, text, and placeholder.
void initialize () override
Prepares the text field renderers and layout state.
void render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline=false) override
Draws the field, text, and caret and processes input.
Size2d getSize () const override
Returns the current rendered size of the field.
Position2d getScreenPosition () const override
Returns the field screen position.
void setScreenPosition (const Position2d &newPosition) override
Sets the field screen position.
const std::string & getText () const
Returns the current text value.
bool isFocused () const
Returns whether the field is currently focused.
std::size_t getCursorIndex () const
Returns the current cursor index.
graphite::UIStyle & style ()
Returns a mutable local style override for this field.
TextField & setText (std::string newText)
Replaces the text content.
TextField & setPlaceholder (std::string newPlaceholder)
Replaces the placeholder string.
TextField & setPadding (Size2d newPadding)
Replaces the inner padding.
TextField & setMaximumWidth (float newMaximumWidth)
Replaces the maximum width before scrolling.
TextField & setFontSize (float newFontSize)
Replaces the explicit font size override.
TextField & setStyle (const graphite::UIStyle &newStyle)
Replaces the local style override.
TextField & setOnChange (ChangeCallback callback)
Registers the callback invoked when text or focus changes.
void focus ()
Gives keyboard focus to the field.
void blur ()
Removes keyboard focus from the field.
Public Member Functions inherited from GameObject
GameObject ()
Construct a new GameObject and assign it a unique ID.
GameObject (const GameObject &other)
GameObject (GameObject &&other) noexcept
GameObject & operator= (const GameObject &other)
GameObject & operator= (GameObject &&other) noexcept
virtual ~GameObject ()
virtual void attachProgram (const ShaderProgram &program)
Attaches a shader program to the object.
virtual void createAndAttachProgram (VertexShader &vertexShader, FragmentShader &fragmentShader)
Creates and attaches a shader program to the object.
virtual void attachTexture (const Texture &texture)
Attaches a texture to the object.
virtual void setColor (const Color &color)
Sets the color of the object.
virtual void setPosition (const Position3d &newPosition)
Sets the position of the object.
virtual void move (const Position3d &deltaPosition)
Moves the object by a certain amount.
virtual void setRotation (const Rotation3d &newRotation)
Sets the rotation of the object.
virtual void lookAt (const Position3d &target, const Normal3d &up)
Sets the object to look at a specific point in 3D space.
virtual void rotate (const Rotation3d &deltaRotation)
Rotates the object by a certain amount.
virtual void setScale (const Scale3d &newScale)
Sets the scale of the object.
virtual void hide ()
Hides the object, making it invisible in the scene.
virtual void show ()
Shows the object, making it visible in the scene.
virtual void onCollisionEnter (GameObject *other)
virtual void onCollisionExit (GameObject *other)
virtual void onCollisionStay (GameObject *other)
virtual void onSignalRecieve (const std::string &signal, GameObject *sender)
virtual void onSignalEnd (const std::string &signal, GameObject *sender)
virtual void onQueryReceive (QueryResult &result)
template<typename T>
void addComponent (T &&existing)
Adds a component to the object.
void beforePhysics () override
template<typename U, typename T>
void addTraitComponent (T &&existing)
Adds a trait component to the object. A trait component is a component that is tied to a specific type of GameObject.
template<typename T>
std::shared_ptr< T > getComponent ()
Gets the first component that matches the specified type.
unsigned int getId () override
Returns the unique identifier associated with this object.
virtual Rotation3d getRotation () const
Returns object rotation in Euler angles.
void addDependency (GameObject *obj)
Adds another object as a dependency for update ordering.
std::vector< GameObject * > getDependencies () const
Returns all registered dependencies for this object.
Public Member Functions inherited from Renderable
virtual void update (Window &window)
Function to update the object each frame.
virtual void setViewMatrix (const glm::mat4 &view)
Function to set the view matrix for the object. Called from Window for internal purposes.
virtual void setProjectionMatrix (const glm::mat4 &projection)
Function to set the projection matrix for the object. Called from Window for internal purposes.
virtual std::optional< std::shared_ptr< opal::Pipeline > > getPipeline ()
virtual void setPipeline (std::shared_ptr< opal::Pipeline > &pipeline)
virtual std::optional< ShaderProgram > getShaderProgram ()
Returns the currently bound shader program, if any.
virtual void setShader (const ShaderProgram &shaderProgram)
Replaces the shader program bound to the renderable.
virtual Position3d getPosition () const
Function to get the position of the object in 3D space.
virtual std::vector< CoreVertex > getVertices () const
Function to get the vertices of the object in 3D space.
virtual Size3d getScale () const
Function to get the scale of the object in 3D space.
virtual bool canCastShadows () const
Function to determine if the object can cast shadows. Can be overridden by derived classes.
virtual ~Renderable ()=default
Public Attributes
std::string text
Current text value.
std::string placeholder
Text shown while the field is empty.
Font font
Font used to render field contents.
Position2d position
Screen-space top-left position of the field.
float fontSize = 0.0f
Explicit font size override. Uses the font's native size when 0.
Size2d padding {.width = 14.0f, .height = 10.0f}
Inner padding applied around the text content.
float maximumWidth = 320.0f
Maximum width available before horizontal scrolling begins.
Color textColor = Color::white()
Color used for committed text.
Color placeholderColor = Color(1.0f, 1.0f, 1.0f, 0.45f)
Color used for placeholder text.
Color backgroundColor = Color(0.08f, 0.09f, 0.12f, 0.94f)
Background fill for the field.
Color borderColor = Color(1.0f, 1.0f, 1.0f, 0.15f)
Border color used while unfocused.
Color focusedBorderColor = Color(1.0f, 0.55f, 0.14f, 1.0f)
Border color used while focused.
Color cursorColor = Color::white()
Color of the insertion cursor.
Public Attributes inherited from GameObject
Rigidbody * rigidbody = nullptr
Cached rigidbody component pointer when attached.
Public Attributes inherited from Renderable
bool renderDepthOfView = false
Whether the object should be included in depth of field calculations. When true, contributes to blur effects.
bool renderLateForward = false
Whether the object must be moved to the late forward rendering pipeline. Objects flagged here are skipped during the primary forward pass and rendered only after all standard forward elements.
Additional Inherited Members
Protected Attributes inherited from GameObject
std::vector< std::shared_ptr< Component > > components
std::vector< GameObject * > dependencies
int id
The unique identifier for the object.
Detailed Description
Single-line editable text input for Graphite interfaces.
Example
TextField nameField(Font::getFont("Inter"), 280.0f, {.x = 24.0f, .y = 24.0f});
nameField.setPlaceholder("Project name");
nameField.setOnChange([](const TextFieldChangeEvent &event) {
    if (event.focused) {
        // React to input while the field is active.
    }
});
Definition at line 59 of file input.h.
Member Typedef Documentation
ChangeCallback
using TextField::ChangeCallback
Initial value:
std::function<void(const TextFieldChangeEvent &)>
Callback invoked when text or focus state changes.
Definition at line 62 of file input.h.
Constructor & Destructor Documentation
TextField() [1/2]
TextField::TextField () default
Constructs an empty text field.
TextField() [2/2]
TextField::TextField (Font font, float maximumWidth, Position2d position = {.x=0.0f,.y=0.0f}, std::string text = "", std::string placeholder = "")
Constructs a text field with font, width, position, text, and placeholder.
References font, maximumWidth, and position.
Member Function Documentation
blur()
void TextField::blur ()
Removes keyboard focus from the field.
focus()
void TextField::focus ()
Gives keyboard focus to the field.
getCursorIndex()
std::size_t TextField::getCursorIndex () const inline
Returns the current cursor index.
Definition at line 125 of file input.h.
{ return cursorIndex; }
getScreenPosition()
Position2d TextField::getScreenPosition () const inline override virtual
Returns the field screen position.
Reimplemented from UIObject.
Definition at line 113 of file input.h.
{ return position; }
References position.
getSize()
Size2d TextField::getSize () const override virtual
Returns the current rendered size of the field.
Reimplemented from UIObject.
getText()
const std::string & TextField::getText () const inline
Returns the current text value.
Definition at line 121 of file input.h.
{ return text; }
References text.
initialize()
void TextField::initialize () override virtual
Prepares the text field renderers and layout state.
Reimplemented from Renderable.
isFocused()
bool TextField::isFocused () const inline
Returns whether the field is currently focused.
Definition at line 123 of file input.h.
{ return focused; }
render()
void TextField::render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline = false) override virtual
Draws the field, text, and caret and processes input.
Implements Renderable.
setFontSize()
TextField & TextField::setFontSize (float newFontSize)
Replaces the explicit font size override.
References TextField().
setMaximumWidth()
TextField & TextField::setMaximumWidth (float newMaximumWidth)
Replaces the maximum width before scrolling.
References TextField().
setOnChange()
TextField & TextField::setOnChange (ChangeCallback callback)
Registers the callback invoked when text or focus changes.
References TextField().
setPadding()
TextField & TextField::setPadding (Size2d newPadding)
Replaces the inner padding.
References TextField().
setPlaceholder()
TextField & TextField::setPlaceholder (std::string newPlaceholder)
Replaces the placeholder string.
References TextField().
setScreenPosition()
void TextField::setScreenPosition (const Position2d & newPosition) inline override virtual
Sets the field screen position.
Implements UIObject.
Definition at line 116 of file input.h.
{
        position = newPosition;
    }
References position.
setStyle()
TextField & TextField::setStyle (const graphite::UIStyle & newStyle)
Replaces the local style override.
References TextField().
setText()
TextField & TextField::setText (std::string newText)
Replaces the text content.
References TextField().
style()
graphite::UIStyle & TextField::style () inline
Returns a mutable local style override for this field.
Definition at line 127 of file input.h.
{
        usesLocalStyle = true;
        return localStyle;
    }
Member Data Documentation
backgroundColor
Color TextField::backgroundColor = Color(0.08f, 0.09f, 0.12f, 0.94f)
Background fill for the field.
Definition at line 84 of file input.h.
borderColor
Color TextField::borderColor = Color(1.0f, 1.0f, 1.0f, 0.15f)
Border color used while unfocused.
Definition at line 86 of file input.h.
cursorColor
Color TextField::cursorColor = Color::white()
Color of the insertion cursor.
Definition at line 90 of file input.h.
focusedBorderColor
Color TextField::focusedBorderColor = Color(1.0f, 0.55f, 0.14f, 1.0f)
Border color used while focused.
Definition at line 88 of file input.h.
font
Font TextField::font
Font used to render field contents.
Definition at line 70 of file input.h.
fontSize
float TextField::fontSize = 0.0f
Explicit font size override. Uses the font's native size when 0.
Definition at line 74 of file input.h.
maximumWidth
float TextField::maximumWidth = 320.0f
Maximum width available before horizontal scrolling begins.
Definition at line 78 of file input.h.
padding
Size2d TextField::padding {.width = 14.0f, .height = 10.0f}
Inner padding applied around the text content.
Definition at line 76 of file input.h.
{.width = 14.0f, .height = 10.0f};
placeholder
std::string TextField::placeholder
Text shown while the field is empty.
Definition at line 68 of file input.h.
placeholderColor
Color TextField::placeholderColor = Color(1.0f, 1.0f, 1.0f, 0.45f)
Color used for placeholder text.
Definition at line 82 of file input.h.
position
Position2d TextField::position
Screen-space top-left position of the field.
Definition at line 72 of file input.h.
text
std::string TextField::text
Current text value.
Definition at line 66 of file input.h.
textColor
Color TextField::textColor = Color::white()
Color used for committed text.
Definition at line 80 of file input.h.
The documentation for this class was generated from the following file:
include/graphite/input.h