Atlas: bezel::Vehicle Class Reference
bezel::Vehicle Class Reference final
High-level vehicle wrapper around Jolt's VehicleConstraint.
#include <bezel.h>
Public Member Functions
Vehicle ()=default
Vehicle (const Vehicle &other)
Vehicle & operator= (const Vehicle &other)
Vehicle (Vehicle &&other) noexcept
Vehicle & operator= (Vehicle &&other) noexcept
void create (std::shared_ptr< PhysicsWorld > world)
void destroy (std::shared_ptr< PhysicsWorld > world)
bool isCreated () const
void setDriverInput (float forward, float right, float brake, float handBrake)
Public Attributes
Rigidbody * chassis = nullptr
VehicleSettings settings
Detailed Description
High-level vehicle wrapper around Jolt's VehicleConstraint.
Example
auto world = std::make_shared<bezel::PhysicsWorld>();
world->init();
auto chassis = std::make_shared<bezel::Rigidbody>();
chassis->mass = 1200.0f;
chassis->setCollider(std::make_shared<bezel::BoxCollider>(Position3d{1.0f,
0.5f, 2.0f})); chassis->create(world);
bezel::Vehicle vehicle;
vehicle.chassis = chassis.get();
vehicle.settings.wheels.resize(4);
vehicle.create(world);
// Each step
vehicle.setDriverInput(1.0f, 0.0f, 0.0f, 0.0f);
world->update(dt);
Definition at line 438 of file bezel.h.
Constructor & Destructor Documentation
Vehicle() [1/3]
bezel::Vehicle::Vehicle () default
Vehicle() [2/3]
bezel::Vehicle::Vehicle (const Vehicle & other)
References Vehicle().
Vehicle() [3/3]
bezel::Vehicle::Vehicle (Vehicle && other) noexcept
References Vehicle().
Member Function Documentation
create()
void bezel::Vehicle::create (std::shared_ptr< PhysicsWorld > world)
destroy()
void bezel::Vehicle::destroy (std::shared_ptr< PhysicsWorld > world)
isCreated()
bool bezel::Vehicle::isCreated () const
operator=() [1/2]
Vehicle & bezel::Vehicle::operator= (const Vehicle & other)
References Vehicle().
operator=() [2/2]
Vehicle & bezel::Vehicle::operator= (Vehicle && other) noexcept
References Vehicle().
setDriverInput()
void bezel::Vehicle::setDriverInput (float forward, float right, float brake, float handBrake)
Member Data Documentation
chassis
Rigidbody* bezel::Vehicle::chassis = nullptr
Definition at line 440 of file bezel.h.
settings
VehicleSettings bezel::Vehicle::settings
Definition at line 441 of file bezel.h.
The documentation for this class was generated from the following file:
include/bezel/bezel.h