Atlas: Checkbox Class Reference
Checkbox Class Reference
Toggleable checkbox with an optional text label.
#include <input.h>
Public Types
using ToggleCallback
Callback invoked when the checked state changes.
Public Member Functions
Checkbox ()=default
Constructs an empty checkbox.
Checkbox (Font font, std::string label="", bool checked=false, Position2d position={.x=0.0f,.y=0.0f})
Constructs a checkbox with font, label, state, and position.
void initialize () override
Prepares the checkbox renderers and label state.
void render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline=false) override
Draws the checkbox and dispatches toggle interaction.
Size2d getSize () const override
Returns the current rendered size of the checkbox row.
Position2d getScreenPosition () const override
Returns the checkbox screen position.
void setScreenPosition (const Position2d &newPosition) override
Sets the checkbox screen position.
const std::string & getLabel () const
Returns the current label.
bool isChecked () const
Returns whether the checkbox is checked.
bool isHovered () const
Returns whether the cursor is currently hovering the checkbox.
bool isEnabled () const
Returns whether the checkbox is enabled.
graphite::UIStyle & style ()
Returns a mutable local style override for this checkbox.
Checkbox & setLabel (std::string newLabel)
Replaces the label text.
Checkbox & setPadding (Size2d newPadding)
Replaces the outer padding.
Checkbox & setBoxSize (float newBoxSize)
Replaces the checkbox square size.
Checkbox & setSpacing (float newSpacing)
Replaces the gap between the box and label.
Checkbox & setFontSize (float newFontSize)
Replaces the explicit font size override.
Checkbox & setStyle (const graphite::UIStyle &newStyle)
Replaces the local style override.
Checkbox & setChecked (bool newChecked)
Sets the checked state directly.
Checkbox & setEnabled (bool newEnabled)
Enables or disables interaction.
Checkbox & setOnToggle (ToggleCallback callback)
Registers the callback invoked when the checkbox toggles.
void toggle ()
Flips the checked state and emits a toggle event.
Public Member Functions inherited from GameObject
GameObject ()
Construct a new GameObject and assign it a unique ID.
GameObject (const GameObject &other)
GameObject (GameObject &&other) noexcept
GameObject & operator= (const GameObject &other)
GameObject & operator= (GameObject &&other) noexcept
virtual ~GameObject ()
virtual void attachProgram (const ShaderProgram &program)
Attaches a shader program to the object.
virtual void createAndAttachProgram (VertexShader &vertexShader, FragmentShader &fragmentShader)
Creates and attaches a shader program to the object.
virtual void attachTexture (const Texture &texture)
Attaches a texture to the object.
virtual void setColor (const Color &color)
Sets the color of the object.
virtual void setPosition (const Position3d &newPosition)
Sets the position of the object.
virtual void move (const Position3d &deltaPosition)
Moves the object by a certain amount.
virtual void setRotation (const Rotation3d &newRotation)
Sets the rotation of the object.
virtual void lookAt (const Position3d &target, const Normal3d &up)
Sets the object to look at a specific point in 3D space.
virtual void rotate (const Rotation3d &deltaRotation)
Rotates the object by a certain amount.
virtual void setScale (const Scale3d &newScale)
Sets the scale of the object.
virtual void hide ()
Hides the object, making it invisible in the scene.
virtual void show ()
Shows the object, making it visible in the scene.
virtual void onCollisionEnter (GameObject *other)
virtual void onCollisionExit (GameObject *other)
virtual void onCollisionStay (GameObject *other)
virtual void onSignalRecieve (const std::string &signal, GameObject *sender)
virtual void onSignalEnd (const std::string &signal, GameObject *sender)
virtual void onQueryReceive (QueryResult &result)
template<typename T>
void addComponent (T &&existing)
Adds a component to the object.
void beforePhysics () override
template<typename U, typename T>
void addTraitComponent (T &&existing)
Adds a trait component to the object. A trait component is a component that is tied to a specific type of GameObject.
template<typename T>
std::shared_ptr< T > getComponent ()
Gets the first component that matches the specified type.
unsigned int getId () override
Returns the unique identifier associated with this object.
virtual Rotation3d getRotation () const
Returns object rotation in Euler angles.
void addDependency (GameObject *obj)
Adds another object as a dependency for update ordering.
std::vector< GameObject * > getDependencies () const
Returns all registered dependencies for this object.
Public Member Functions inherited from Renderable
virtual void update (Window &window)
Function to update the object each frame.
virtual void setViewMatrix (const glm::mat4 &view)
Function to set the view matrix for the object. Called from Window for internal purposes.
virtual void setProjectionMatrix (const glm::mat4 &projection)
Function to set the projection matrix for the object. Called from Window for internal purposes.
virtual std::optional< std::shared_ptr< opal::Pipeline > > getPipeline ()
virtual void setPipeline (std::shared_ptr< opal::Pipeline > &pipeline)
virtual std::optional< ShaderProgram > getShaderProgram ()
Returns the currently bound shader program, if any.
virtual void setShader (const ShaderProgram &shaderProgram)
Replaces the shader program bound to the renderable.
virtual Position3d getPosition () const
Function to get the position of the object in 3D space.
virtual std::vector< CoreVertex > getVertices () const
Function to get the vertices of the object in 3D space.
virtual Size3d getScale () const
Function to get the scale of the object in 3D space.
virtual bool canCastShadows () const
Function to determine if the object can cast shadows. Can be overridden by derived classes.
virtual ~Renderable ()=default
Public Attributes
std::string label
Label displayed next to the checkbox.
Font font
Font used to render the label.
Position2d position
Screen-space top-left position of the checkbox.
float fontSize = 0.0f
Explicit font size override. Uses the font's native size when 0.
Size2d padding {.width = 0.0f, .height = 4.0f}
Extra padding around the checkbox row.
float boxSize = 28.0f
Size of the square check box.
float spacing = 12.0f
Gap between the box and the label.
bool checked = false
Current checked state.
bool enabled = true
Whether the checkbox can currently be interacted with.
Color textColor = Color::white()
Label color.
Color boxBackgroundColor = Color(0.12f, 0.13f, 0.17f, 0.96f)
Default fill color for the box.
Color hoverBoxBackgroundColor = Color(0.17f, 0.18f, 0.23f, 0.98f)
Fill color used while hovered.
Color borderColor = Color(1.0f, 1.0f, 1.0f, 0.18f)
Default border color.
Color activeBorderColor = Color(1.0f, 0.55f, 0.14f, 1.0f)
Border color used while checked or hovered in the active state.
Color checkColor = Color(1.0f, 0.55f, 0.14f, 1.0f)
Color used for the check mark.
Public Attributes inherited from GameObject
Rigidbody * rigidbody = nullptr
Cached rigidbody component pointer when attached.
Public Attributes inherited from Renderable
bool renderDepthOfView = false
Whether the object should be included in depth of field calculations. When true, contributes to blur effects.
bool renderLateForward = false
Whether the object must be moved to the late forward rendering pipeline. Objects flagged here are skipped during the primary forward pass and rendered only after all standard forward elements.
Additional Inherited Members
Protected Attributes inherited from GameObject
std::vector< std::shared_ptr< Component > > components
std::vector< GameObject * > dependencies
int id
The unique identifier for the object.
Detailed Description
Toggleable checkbox with an optional text label.
Example
Checkbox shadows(Font::getFont("Inter"), "Shadows", true,
                 {.x = 24.0f, .y = 120.0f});
shadows.setOnToggle([](const CheckboxToggleEvent &event) {
    // Use event.checked to update application state.
});
Definition at line 286 of file input.h.
Member Typedef Documentation
ToggleCallback
using Checkbox::ToggleCallback
Initial value:
std::function<void(const CheckboxToggleEvent &)>
Callback invoked when the checked state changes.
Definition at line 289 of file input.h.
Constructor & Destructor Documentation
Checkbox() [1/2]
Checkbox::Checkbox () default
Constructs an empty checkbox.
Checkbox() [2/2]
Checkbox::Checkbox (Font font, std::string label = "", bool checked = false, Position2d position = {.x=0.0f,.y=0.0f})
Constructs a checkbox with font, label, state, and position.
References checked, font, label, and position.
Member Function Documentation
getLabel()
const std::string & Checkbox::getLabel () const inline
Returns the current label.
Definition at line 346 of file input.h.
{ return label; }
References label.
getScreenPosition()
Position2d Checkbox::getScreenPosition () const inline override virtual
Returns the checkbox screen position.
Reimplemented from UIObject.
Definition at line 339 of file input.h.
{ return position; }
References position.
getSize()
Size2d Checkbox::getSize () const override virtual
Returns the current rendered size of the checkbox row.
Reimplemented from UIObject.
initialize()
void Checkbox::initialize () override virtual
Prepares the checkbox renderers and label state.
Reimplemented from Renderable.
isChecked()
bool Checkbox::isChecked () const inline
Returns whether the checkbox is checked.
Definition at line 348 of file input.h.
{ return checked; }
References checked.
isEnabled()
bool Checkbox::isEnabled () const inline
Returns whether the checkbox is enabled.
Definition at line 352 of file input.h.
{ return enabled; }
References enabled.
isHovered()
bool Checkbox::isHovered () const inline
Returns whether the cursor is currently hovering the checkbox.
Definition at line 350 of file input.h.
{ return hovered; }
render()
void Checkbox::render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline = false) override virtual
Draws the checkbox and dispatches toggle interaction.
Implements Renderable.
setBoxSize()
Checkbox & Checkbox::setBoxSize (float newBoxSize)
Replaces the checkbox square size.
References Checkbox().
setChecked()
Checkbox & Checkbox::setChecked (bool newChecked)
Sets the checked state directly.
References Checkbox().
setEnabled()
Checkbox & Checkbox::setEnabled (bool newEnabled)
Enables or disables interaction.
References Checkbox().
setFontSize()
Checkbox & Checkbox::setFontSize (float newFontSize)
Replaces the explicit font size override.
References Checkbox().
setLabel()
Checkbox & Checkbox::setLabel (std::string newLabel)
Replaces the label text.
References Checkbox().
setOnToggle()
Checkbox & Checkbox::setOnToggle (ToggleCallback callback)
Registers the callback invoked when the checkbox toggles.
References Checkbox().
setPadding()
Checkbox & Checkbox::setPadding (Size2d newPadding)
Replaces the outer padding.
References Checkbox().
setScreenPosition()
void Checkbox::setScreenPosition (const Position2d & newPosition) inline override virtual
Sets the checkbox screen position.
Implements UIObject.
Definition at line 341 of file input.h.
{
        position = newPosition;
    }
References position.
setSpacing()
Checkbox & Checkbox::setSpacing (float newSpacing)
Replaces the gap between the box and label.
References Checkbox().
setStyle()
Checkbox & Checkbox::setStyle (const graphite::UIStyle & newStyle)
Replaces the local style override.
References Checkbox().
style()
graphite::UIStyle & Checkbox::style () inline
Returns a mutable local style override for this checkbox.
Definition at line 354 of file input.h.
{
        usesLocalStyle = true;
        return localStyle;
    }
toggle()
void Checkbox::toggle ()
Flips the checked state and emits a toggle event.
References style().
Member Data Documentation
activeBorderColor
Color Checkbox::activeBorderColor = Color(1.0f, 0.55f, 0.14f, 1.0f)
Border color used while checked or hovered in the active state.
Definition at line 319 of file input.h.
borderColor
Color Checkbox::borderColor = Color(1.0f, 1.0f, 1.0f, 0.18f)
Default border color.
Definition at line 317 of file input.h.
boxBackgroundColor
Color Checkbox::boxBackgroundColor = Color(0.12f, 0.13f, 0.17f, 0.96f)
Default fill color for the box.
Definition at line 313 of file input.h.
boxSize
float Checkbox::boxSize = 28.0f
Size of the square check box.
Definition at line 303 of file input.h.
checkColor
Color Checkbox::checkColor = Color(1.0f, 0.55f, 0.14f, 1.0f)
Color used for the check mark.
Definition at line 321 of file input.h.
checked
bool Checkbox::checked = false
Current checked state.
Definition at line 307 of file input.h.
enabled
bool Checkbox::enabled = true
Whether the checkbox can currently be interacted with.
Definition at line 309 of file input.h.
font
Font Checkbox::font
Font used to render the label.
Definition at line 295 of file input.h.
fontSize
float Checkbox::fontSize = 0.0f
Explicit font size override. Uses the font's native size when 0.
Definition at line 299 of file input.h.
hoverBoxBackgroundColor
Color Checkbox::hoverBoxBackgroundColor = Color(0.17f, 0.18f, 0.23f, 0.98f)
Fill color used while hovered.
Definition at line 315 of file input.h.
label
std::string Checkbox::label
Label displayed next to the checkbox.
Definition at line 293 of file input.h.
padding
Size2d Checkbox::padding {.width = 0.0f, .height = 4.0f}
Extra padding around the checkbox row.
Definition at line 301 of file input.h.
{.width = 0.0f, .height = 4.0f};
position
Position2d Checkbox::position
Screen-space top-left position of the checkbox.
Definition at line 297 of file input.h.
spacing
float Checkbox::spacing = 12.0f
Gap between the box and the label.
Definition at line 305 of file input.h.
textColor
Color Checkbox::textColor = Color::white()
Label color.
Definition at line 311 of file input.h.
The documentation for this class was generated from the following file:
include/graphite/input.h