Atlas: Blur Class Reference
Blur Class Reference
Post-processing effect that applies a Gaussian blur to the rendered image. The blur magnitude can be controlled.
#include <effect.h>
Public Member Functions
Blur (float magnitude=16.0)
Constructs a new Blur effect.
void applyToProgram (ShaderProgram &program, int index) override
Applies the blur magnitude to the shader program.
Public Member Functions inherited from Effect
Effect (RenderTargetEffect t)
Constructs a new Effect object.
Static Public Member Functions
static std::shared_ptr< Blur > create (float magnitude=16.0)
Creates a shared pointer to a Blur effect.
Public Attributes
float magnitude = 16.0
The magnitude (radius) of the blur effect.
Public Attributes inherited from Effect
RenderTargetEffect type
The type of effect this instance represents.
Detailed Description
Post-processing effect that applies a Gaussian blur to the rendered image. The blur magnitude can be controlled.
Definition at line 159 of file effect.h.
Constructor & Destructor Documentation
Blur()
Blur::Blur (float magnitude = 16.0) inline
Constructs a new Blur effect.
Parameters
magnitude The blur radius. Higher values create stronger blur.
Definition at line 171 of file effect.h.
        : Effect(RenderTargetEffect::Blur), magnitude(magnitude) {}
References Blur(), Effect::Effect(), and magnitude.
Member Function Documentation
applyToProgram()
void Blur::applyToProgram (ShaderProgram & program, int index) inline override virtual
Applies the blur magnitude to the shader program.
Parameters
program The shader program to apply the effect to.
index The index of the effect in the effect array.
Reimplemented from Effect.
Definition at line 188 of file effect.h.
{
        program.setUniform1f("EffectFloat1[" + std::to_string((int)index) + "]",
                             magnitude);
    }
References magnitude, and ShaderProgram::setUniform1f().
create()
std::shared_ptr< Blur > Blur::create (float magnitude = 16.0) inline static
Creates a shared pointer to a Blur effect.
Parameters
magnitude The blur radius.
Returns
(std::shared_ptr<Blur>) The created blur effect.
Definition at line 179 of file effect.h.
{
        return std::make_shared<Blur>(magnitude);
    }
References magnitude.
Member Data Documentation
magnitude
float Blur::magnitude = 16.0
The magnitude (radius) of the blur effect.
Definition at line 165 of file effect.h.
The documentation for this class was generated from the following file:
include/atlas/effect.h