Atlas: GameObject Class Reference
GameObject Class Reference
Base class for all Game Objects. It extends from Renderable and it provides common functionality for all game objects in the scene.
#include <component.h>
Public Member Functions
GameObject ()
Construct a new GameObject and assign it a unique ID.
GameObject (const GameObject &other)
GameObject (GameObject &&other) noexcept
GameObject & operator= (const GameObject &other)
GameObject & operator= (GameObject &&other) noexcept
virtual ~GameObject ()
virtual void attachProgram (const ShaderProgram &program)
Attaches a shader program to the object.
virtual void createAndAttachProgram (VertexShader &vertexShader, FragmentShader &fragmentShader)
Creates and attaches a shader program to the object.
virtual void attachTexture (const Texture &texture)
Attaches a texture to the object.
virtual void setColor (const Color &color)
Sets the color of the object.
virtual void setPosition (const Position3d &newPosition)
Sets the position of the object.
virtual void move (const Position3d &deltaPosition)
Moves the object by a certain amount.
virtual void setRotation (const Rotation3d &newRotation)
Sets the rotation of the object.
virtual void lookAt (const Position3d &target, const Normal3d &up)
Sets the object to look at a specific point in 3D space.
virtual void rotate (const Rotation3d &deltaRotation)
Rotates the object by a certain amount.
virtual void setScale (const Scale3d &newScale)
Sets the scale of the object.
virtual void hide ()
Hides the object, making it invisible in the scene.
virtual void show ()
Shows the object, making it visible in the scene.
virtual void onCollisionEnter (GameObject *other)
virtual void onCollisionExit (GameObject *other)
virtual void onCollisionStay (GameObject *other)
virtual void onSignalRecieve (const std::string &signal, GameObject *sender)
virtual void onSignalEnd (const std::string &signal, GameObject *sender)
virtual void onQueryRecieve (QueryResult &result)
template<typename T>
void addComponent (T &&existing)
Adds a component to the object.
void beforePhysics () override
template<typename U, typename T>
void addTraitComponent (T &&existing)
Adds a trait component to the object. A trait component is a component that is tied to a specific type of GameObject.
template<typename T>
std::shared_ptr< T > getComponent ()
Gets the first component that matches the specified type.
unsigned int getId () override
Returns the unique identifier associated with this object.
virtual Rotation3d getRotation () const
void addDependency (GameObject *obj)
std::vector< GameObject * > getDependencies () const
Public Member Functions inherited from Renderable
virtual void render (float dt, std::shared_ptr< opal::CommandBuffer > commandBuffer, bool updatePipeline=false)=0
Function to render the object. Must be implemented by derived classes.
virtual void initialize ()
Function to initialize the object. Can be overridden by derived.
virtual void update (Window &window)
Function to update the object each frame.
virtual void setViewMatrix (const glm::mat4 &view)
Function to set the view matrix for the object. Called from Window for internal purposes.
virtual void setProjectionMatrix (const glm::mat4 &projection)
Function to set the projection matrix for the object. Called from Window for internal purposes.
virtual std::optional< std::shared_ptr< opal::Pipeline > > getPipeline ()
virtual void setPipeline (std::shared_ptr< opal::Pipeline > &pipeline)
virtual std::optional< ShaderProgram > getShaderProgram ()
Returns the currently bound shader program, if any.
virtual void setShader (const ShaderProgram &shaderProgram)
Replaces the shader program bound to the renderable.
virtual Position3d getPosition () const
Function to get the position of the object in 3D space.
virtual std::vector< CoreVertex > getVertices () const
Function to get the vertices of the object in 3D space.
virtual Size3d getScale () const
Function to get the scale of the object in 3D space.
virtual bool canCastShadows () const
Function to determine if the object can cast shadows. Can be overridden by derived classes.
virtual ~Renderable ()=default
virtual bool canUseDeferredRendering ()
Function to determine if the object can use deferred rendering.
Public Attributes
Rigidbody * rigidbody = nullptr
Public Attributes inherited from Renderable
bool renderDepthOfView = false
Whether the object should be included in depth of field calculations. When true, contributes to blur effects.
bool renderLateForward = false
Whether the object must be moved to the late forward rendering pipeline. Objects flagged here are skipped during the primary forward pass and rendered only after all standard forward elements.
Protected Attributes
std::vector< std::shared_ptr< Component > > components
std::vector< GameObject * > dependencies
int id
The unique identifier for the object.
Detailed Description
Base class for all Game Objects. It extends from Renderable and it provides common functionality for all game objects in the scene.
Definition at line 177 of file component.h.
Constructor & Destructor Documentation
GameObject() [1/3]
GameObject::GameObject () inline
Construct a new GameObject and assign it a unique ID.
Definition at line 182 of file component.h.
                 {
        std::random_device rd;
        std::mt19937 gen(rd());
        std::uniform_int_distribution<int> dist(0, INT_MAX);
        id = dist(gen);
        atlas::gameObjects[id] = this;
    }
References atlas::gameObjects, and id.
GameObject() [2/3]
GameObject::GameObject (const GameObject & other) inline
Definition at line 191 of file component.h.
{
        std::random_device rd;
        std::mt19937 gen(rd());
        std::uniform_int_distribution<int> dist(0, INT_MAX);
        id = dist(gen);
        atlas::gameObjects[id] = this;
    }
References GameObject(), atlas::gameObjects, and id.
GameObject() [3/3]
GameObject::GameObject (GameObject && other) inline noexcept
Definition at line 200 of file component.h.
{
        std::random_device rd;
        std::mt19937 gen(rd());
        std::uniform_int_distribution<int> dist(0, INT_MAX);
        id = dist(gen);
        atlas::gameObjects[id] = this;
    }
References GameObject(), atlas::gameObjects, and id.
~GameObject()
virtual GameObject::~GameObject () inline virtual
Definition at line 223 of file component.h.
{ atlas::gameObjects.erase(id); }
References atlas::gameObjects.
Member Function Documentation
addComponent()
template<typename T> void GameObject::addComponent (T && existing) inline
Adds a component to the object.
Template Parameters
T The type of component to add.
Parameters
existing The component instance to add.
Warning
It must be long-lived. This means that declaring it as a class property is a good idea.
Definition at line 323 of file component.h.
{
        using U = std::remove_cvref_t<T>;
        std::shared_ptr<U> component =
            std::make_shared<U>(std::forward<T>(existing));
        component->object = this;
        component->atAttach();
        components.push_back(component);
    }
References components, and U.
addDependency()
void GameObject::addDependency (GameObject * obj) inline
Definition at line 391 of file component.h.
{ dependencies.push_back(obj); }
References dependencies, and GameObject().
addTraitComponent()
template<typename U, typename T> void GameObject::addTraitComponent (T && existing) inline
Adds a trait component to the object. A trait component is a component that is tied to a specific type of GameObject.
Template Parameters
U The type of GameObject the trait component is tied to.
T The type of trait component to add.
Parameters
existing The trait component instance to add.
Warning
It must be long-lived. This means that declaring it as a class property is a good idea.
Definition at line 350 of file component.h.
{
        if (static_cast<U *>(this) == nullptr) {
            throw std::runtime_error(
                "Cannot add TraitComponent to object that is not of the "
                "correct type.");
        }
        existing.setTypedObject(static_cast<U *>(this));
        std::shared_ptr<T> component =
            std::make_shared<T>(std::forward<T>(existing));
        component->object = this;
        components.push_back(component);
    }
References components, and U.
attachProgram()
virtual void GameObject::attachProgram (const ShaderProgram & program) inline virtual
Attaches a shader program to the object.
Parameters
program
Reimplemented in CoreObject.
Definition at line 230 of file component.h.
{
    };
attachTexture()
virtual void GameObject::attachTexture (const Texture & texture) inline virtual
Attaches a texture to the object.
Parameters
texture The texture to attach.
Reimplemented in CoreObject, Model, and ParticleEmitter.
Definition at line 246 of file component.h.
{};
beforePhysics()
void GameObject::beforePhysics () inline override virtual
Reimplemented from Renderable.
Definition at line 332 of file component.h.
{
        for (auto &component : components) {
            component->beforePhysics();
        }
    }
References components.
createAndAttachProgram()
virtual void GameObject::createAndAttachProgram (VertexShader & vertexShader, FragmentShader & fragmentShader) inline virtual
Creates and attaches a shader program to the object.
Parameters
vertexShader The vertex shader for the program
fragmentShader The fragment shader for the program
Reimplemented in CoreObject.
Definition at line 239 of file component.h.
                                                                            {};
getComponent()
template<typename T> std::shared_ptr< T > GameObject::getComponent () inline
Gets the first component that matches the specified type.
Template Parameters
T The type of component to get.
Returns
(std::shared_ptr<T>) A shared pointer to the component if found, or nullptr if not found.
Definition at line 372 of file component.h.
{
        for (auto &component : components) {
            std::shared_ptr<T> casted = std::dynamic_pointer_cast<T>(component);
            if (casted != nullptr) {
                return casted;
            }
        }
        return nullptr;
    }
References components.
getDependencies()
std::vector< GameObject * > GameObject::getDependencies () const inline
Definition at line 393 of file component.h.
{ return dependencies; }
References dependencies.
getId()
unsigned int GameObject::getId () inline override virtual
Returns the unique identifier associated with this object.
Reimplemented from Renderable.
Definition at line 387 of file component.h.
{ return id; }
References id.
getRotation()
virtual Rotation3d GameObject::getRotation () const inline virtual
Reimplemented in CoreObject.
Definition at line 389 of file component.h.
{ return Rotation3d(0.f, 0.f, 0.f); }
hide()
virtual void GameObject::hide () inline virtual
Hides the object, making it invisible in the scene.
Reimplemented in CompoundObject, and CoreObject.
Definition at line 295 of file component.h.
{};
lookAt()
virtual void GameObject::lookAt (const Position3d & target, const Normal3d & up) inline virtual
Sets the object to look at a specific point in 3D space.
Parameters
target The point to look at.
up The up vector to define the orientation.
Reimplemented in CompoundObject, and CoreObject.
Definition at line 277 of file component.h.
                                                             {};
move()
virtual void GameObject::move (const Position3d & deltaPosition) inline virtual
Moves the object by a certain amount.
Parameters
deltaPosition The amount to move the object by.
Reimplemented in CompoundObject, CoreObject, Fluid, Model, ParticleEmitter, and Terrain.
Definition at line 264 of file component.h.
{};
onCollisionEnter()
virtual void GameObject::onCollisionEnter (GameObject * other) inline virtual
Reimplemented in CoreObject.
Definition at line 302 of file component.h.
{}
References GameObject().
onCollisionExit()
virtual void GameObject::onCollisionExit (GameObject * other) inline virtual
Reimplemented in CoreObject.
Definition at line 303 of file component.h.
{}
References GameObject().
onCollisionStay()
virtual void GameObject::onCollisionStay (GameObject * other) inline virtual
Reimplemented in CoreObject.
Definition at line 304 of file component.h.
{}
References GameObject().
onQueryRecieve()
virtual void GameObject::onQueryRecieve (QueryResult & result) inline virtual
Reimplemented in CoreObject.
Definition at line 311 of file component.h.
{}
onSignalEnd()
virtual void GameObject::onSignalEnd (const std::string & signal, GameObject * sender) inline virtual
Reimplemented in CoreObject.
Definition at line 308 of file component.h.
                                                                  {}
References GameObject().
onSignalRecieve()
virtual void GameObject::onSignalRecieve (const std::string & signal, GameObject * sender) inline virtual
Reimplemented in CoreObject.
Definition at line 306 of file component.h.
                                                                      {}
References GameObject().
operator=() [1/2]
GameObject & GameObject::operator= (const GameObject & other) inline
Definition at line 209 of file component.h.
{
        if (this != &other) {
            atlas::gameObjects[id] = this;
        }
        return *this;
    }
References GameObject(), atlas::gameObjects, and id.
operator=() [2/2]
GameObject & GameObject::operator= (GameObject && other) inline noexcept
Definition at line 216 of file component.h.
{
        if (this != &other) {
            atlas::gameObjects[id] = this;
        }
        return *this;
    }
References GameObject(), atlas::gameObjects, and id.
rotate()
virtual void GameObject::rotate (const Rotation3d & deltaRotation) inline virtual
Rotates the object by a certain amount.
Parameters
deltaRotation The amount to rotate the object by.
Reimplemented in CompoundObject, CoreObject, Fluid, and Terrain.
Definition at line 284 of file component.h.
{};
setColor()
virtual void GameObject::setColor (const Color & color) inline virtual
Sets the color of the object.
Parameters
color The new color to set.
Reimplemented in CoreObject, and ParticleEmitter.
Definition at line 252 of file component.h.
{};
setPosition()
virtual void GameObject::setPosition (const Position3d & newPosition) inline virtual
Sets the position of the object.
Parameters
newPosition The new position to set.
Reimplemented in CompoundObject, CoreObject, Fluid, Model, ParticleEmitter, and Terrain.
Definition at line 258 of file component.h.
{};
setRotation()
virtual void GameObject::setRotation (const Rotation3d & newRotation) inline virtual
Sets the rotation of the object.
Parameters
newRotation The new rotation to set.
Reimplemented in CompoundObject, CoreObject, Fluid, Model, and Terrain.
Definition at line 270 of file component.h.
{};
setScale()
virtual void GameObject::setScale (const Scale3d & newScale) inline virtual
Sets the scale of the object.
Parameters
newScale The new scale of the object.
Reimplemented in CompoundObject, CoreObject, Fluid, Model, and Terrain.
Definition at line 290 of file component.h.
{};
show()
virtual void GameObject::show () inline virtual
Shows the object, making it visible in the scene.
Reimplemented in CompoundObject, and CoreObject.
Definition at line 300 of file component.h.
{};
Member Data Documentation
components
std::vector<std::shared_ptr<Component> > GameObject::components protected
Definition at line 396 of file component.h.
dependencies
std::vector<GameObject *> GameObject::dependencies protected
Definition at line 397 of file component.h.
id
int GameObject::id protected
The unique identifier for the object.
Definition at line 402 of file component.h.
rigidbody
Rigidbody* GameObject::rigidbody = nullptr
Definition at line 382 of file component.h.
The documentation for this class was generated from the following file:
include/atlas/component.h