#!/bin/bash

set -e

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <metal-files-dir> <output-swift-file>"
  exit 1
fi

METAL_DIR="${1#file://}"
OUTPUT_SWIFT="${2#file://}"
CONST_NAME="allMetalShaders"

PRIORITY_FILES=(
  "Lighting.metal"
  "Common.metal"
)

echo "// This file is autogenerated. Do not edit manually." > "$OUTPUT_SWIFT"
echo "import Foundation" >> "$OUTPUT_SWIFT"
echo "" >> "$OUTPUT_SWIFT"
echo "let $CONST_NAME: String = \"\"\"" >> "$OUTPUT_SWIFT"

for file in "${PRIORITY_FILES[@]}"; do
  full_path="$METAL_DIR/$file"
  if [ -f "$full_path" ]; then
    echo "// Contents of $file" >> "$OUTPUT_SWIFT"
    cat "$full_path" >> "$OUTPUT_SWIFT"
    echo -e "\n" >> "$OUTPUT_SWIFT"
  else
    echo "⚠️ Warning: Priority file '$file' not found. Skipping."
  fi
done

DEFINITIONS="$METAL_DIR/Definitions.metal"
if [ -f "$DEFINITIONS" ]; then
  echo "// Contents of Definitions.metal" >> "$OUTPUT_SWIFT"
  cat "$DEFINITIONS" >> "$OUTPUT_SWIFT"
  echo -e "\n" >> "$OUTPUT_SWIFT"
fi

all_files=$(find "$METAL_DIR" -type f -name "*.metal")

for file in $all_files; do
  base="$(basename "$file")"
  skip=0
  for p in "${PRIORITY_FILES[@]}"; do
    [[ "$base" == "$p" ]] && skip=1
  done
  [[ "$base" == "Definitions.metal" ]] && skip=1

  if [ "$skip" -eq 0 ]; then
    echo "// Contents of $base" >> "$OUTPUT_SWIFT"
    cat "$file" >> "$OUTPUT_SWIFT"
    echo -e "\n" >> "$OUTPUT_SWIFT"
  fi
done

echo "\"\"\"" >> "$OUTPUT_SWIFT"

count=$(find "$METAL_DIR" -type f -name "*.metal" | wc -l)
echo "✅ Generated $OUTPUT_SWIFT with contents of $count .metal files."
