#!/bin/bash

set -e

if [ "$#" -ne 2 ]; then
  echo "Usage: $0 <metal-files-dir> <output-swift-file>"
  exit 1
fi

METAL_DIR="${1#file://}"
OUTPUT_SWIFT="${2#file://}"

CONST_NAME="allMetalShaders"

metal_files=$(find "$METAL_DIR" -type f -name "*.metal")

echo "// This file is autogenerated. Do not edit manually." > "$OUTPUT_SWIFT"
echo "import Foundation" >> "$OUTPUT_SWIFT"
echo "" >> "$OUTPUT_SWIFT"
echo "let $CONST_NAME: String = \"\"\"" >> "$OUTPUT_SWIFT"

for file in $metal_files; do
  echo "// Contents of $(basename "$file")" >> "$OUTPUT_SWIFT"
  cat "$file" >> "$OUTPUT_SWIFT"
  echo -e "\n" >> "$OUTPUT_SWIFT"  # Add newline between files
done

echo "\"\"\"" >> "$OUTPUT_SWIFT"

echo "✅ Generated $OUTPUT_SWIFT with contents of $(echo "$metal_files" | wc -l) .metal files."
