var hierarchy =
[
    [ "AmbientLight", "struct_ambient_light.html", null ],
    [ "AreaLight", "struct_area_light.html", null ],
    [ "Atmosphere", "class_atmosphere.html", null ],
    [ "opal::Attachment", "classopal_1_1_attachment.html", null ],
    [ "AudioData", "class_audio_data.html", null ],
    [ "AudioEffect", "class_audio_effect.html", [
      [ "Distortion", "class_distortion.html", null ],
      [ "Echo", "class_echo.html", null ],
      [ "Reverb", "class_reverb.html", null ]
    ] ],
    [ "AudioEngine", "class_audio_engine.html", null ],
    [ "AudioSource", "class_audio_source.html", null ],
    [ "Biome", "class_biome.html", null ],
    [ "BloomElement", "struct_bloom_element.html", null ],
    [ "BloomRenderTarget", "class_bloom_render_target.html", null ],
    [ "Body", "class_body.html", null ],
    [ "Bounds", "class_bounds.html", null ],
    [ "opal::Buffer", "classopal_1_1_buffer.html", null ],
    [ "Camera", "class_camera.html", null ],
    [ "Character", "struct_character.html", null ],
    [ "CheckerTile", "struct_checker_tile.html", null ],
    [ "ChromaticAberrationParameters", "struct_chromatic_aberration_parameters.html", null ],
    [ "Clouds", "class_clouds.html", null ],
    [ "CollisionPair", "struct_collision_pair.html", null ],
    [ "Color", "struct_color.html", null ],
    [ "ColorCorrectionParameters", "struct_color_correction_parameters.html", null ],
    [ "opal::CommandBuffer", "classopal_1_1_command_buffer.html", null ],
    [ "Component", "class_component.html", [
      [ "AudioPlayer", "class_audio_player.html", null ],
      [ "TraitComponent< T >", "class_trait_component.html", null ]
    ] ],
    [ "Contact", "struct_contact.html", null ],
    [ "opal::Context", "classopal_1_1_context.html", null ],
    [ "opal::ContextConfiguration", "structopal_1_1_context_configuration.html", null ],
    [ "CoreVertex", "struct_core_vertex.html", null ],
    [ "Cubemap", "struct_cubemap.html", null ],
    [ "opal::DepthStencilBuffer", "classopal_1_1_depth_stencil_buffer.html", null ],
    [ "opal::Device", "classopal_1_1_device.html", null ],
    [ "opal::DeviceInfo", "structopal_1_1_device_info.html", null ],
    [ "DilationParameters", "struct_dilation_parameters.html", null ],
    [ "DirectionalLight", "class_directional_light.html", null ],
    [ "opal::DrawingState", "structopal_1_1_drawing_state.html", null ],
    [ "Edge", "struct_edge.html", null ],
    [ "Effect", "class_effect.html", [
      [ "Blur", "class_blur.html", null ],
      [ "ChromaticAberration", "class_chromatic_aberration.html", null ],
      [ "ColorCorrection", "class_color_correction.html", null ],
      [ "Dilation", "class_dilation.html", null ],
      [ "EdgeDetection", "class_edge_detection.html", null ],
      [ "FilmGrain", "class_film_grain.html", null ],
      [ "Grayscale", "class_grayscale.html", null ],
      [ "Inversion", "class_inversion.html", null ],
      [ "MotionBlur", "class_motion_blur.html", null ],
      [ "Pixelation", "class_pixelation.html", null ],
      [ "Posterization", "class_posterization.html", null ],
      [ "Sharpen", "class_sharpen.html", null ]
    ] ],
    [ "Environment", "class_environment.html", null ],
    [ "FilmGrainParameters", "struct_film_grain_parameters.html", null ],
    [ "Fog", "struct_fog.html", null ],
    [ "Font", "struct_font.html", null ],
    [ "FractalNoise", "class_fractal_noise.html", null ],
    [ "FragmentShader", "struct_fragment_shader.html", null ],
    [ "opal::Framebuffer", "classopal_1_1_framebuffer.html", null ],
    [ "GeometryShader", "struct_geometry_shader.html", null ],
    [ "GPUAreaLight", "struct_g_p_u_area_light.html", null ],
    [ "GPUDirectionalLight", "struct_g_p_u_directional_light.html", null ],
    [ "GPUPointLight", "struct_g_p_u_point_light.html", null ],
    [ "GPUShadowParams", "struct_g_p_u_shadow_params.html", null ],
    [ "GPUSpotLight", "struct_g_p_u_spot_light.html", null ],
    [ "Instance", "struct_instance.html", null ],
    [ "Interactive", "class_interactive.html", null ],
    [ "IntersectionPoint", "struct_intersection_point.html", null ],
    [ "LayoutDescriptor", "struct_layout_descriptor.html", null ],
    [ "Light", "struct_light.html", null ],
    [ "LightBloom", "struct_light_bloom.html", null ],
    [ "Material", "struct_material.html", null ],
    [ "Monitor", "class_monitor.html", null ],
    [ "MotionBlurParameters", "struct_motion_blur_parameters.html", null ],
    [ "MousePacket", "struct_mouse_packet.html", null ],
    [ "MouseScrollPacket", "struct_mouse_scroll_packet.html", null ],
    [ "Noise", "class_noise.html", null ],
    [ "Particle", "struct_particle.html", null ],
    [ "ParticleSettings", "struct_particle_settings.html", null ],
    [ "PerlinNoise", "struct_perlin_noise.html", null ],
    [ "opal::Pipeline", "classopal_1_1_pipeline.html", null ],
    [ "PixelationParameters", "struct_pixelation_parameters.html", null ],
    [ "Point", "struct_point.html", null ],
    [ "PointLightConstants", "struct_point_light_constants.html", null ],
    [ "Position2d", "struct_position2d.html", null ],
    [ "Position3d", "struct_position3d.html", null ],
    [ "PosterizationParameters", "struct_posterization_parameters.html", null ],
    [ "PseudoBody", "struct_pseudo_body.html", null ],
    [ "Radians", "struct_radians.html", null ],
    [ "Renderable", "class_renderable.html", [
      [ "GameObject", "class_game_object.html", [
        [ "CompoundObject", "class_compound_object.html", null ],
        [ "CoreObject", "class_core_object.html", null ],
        [ "Fluid", "struct_fluid.html", null ],
        [ "Model", "class_model.html", null ],
        [ "ParticleEmitter", "class_particle_emitter.html", null ],
        [ "Terrain", "class_terrain.html", null ],
        [ "UIObject", "class_u_i_object.html", [
          [ "Text", "class_text.html", null ],
          [ "UIView", "class_u_i_view.html", null ]
        ] ]
      ] ],
      [ "RenderTarget", "class_render_target.html", null ],
      [ "Skybox", "class_skybox.html", null ]
    ] ],
    [ "opal::RenderPass", "classopal_1_1_render_pass.html", null ],
    [ "opal::ResolveAction", "classopal_1_1_resolve_action.html", null ],
    [ "Resource", "struct_resource.html", null ],
    [ "ResourceGroup", "struct_resource_group.html", null ],
    [ "RimLight", "struct_rim_light.html", null ],
    [ "Rotation3d", "struct_rotation3d.html", null ],
    [ "Scene", "class_scene.html", null ],
    [ "opal::Shader", "classopal_1_1_shader.html", null ],
    [ "opal::ShaderProgram", "classopal_1_1_shader_program.html", null ],
    [ "ShaderProgram", "struct_shader_program.html", null ],
    [ "ShadowParams", "struct_shadow_params.html", null ],
    [ "Shape", "class_shape.html", [
      [ "Box", "class_box.html", null ],
      [ "Convex", "class_convex.html", null ],
      [ "Sphere", "class_sphere.html", null ]
    ] ],
    [ "SimplexNoise", "class_simplex_noise.html", null ],
    [ "Size2d", "struct_size2d.html", null ],
    [ "Spotlight", "struct_spotlight.html", null ],
    [ "TerrainGenerator", "class_terrain_generator.html", [
      [ "CompoundGenerator", "class_compound_generator.html", null ],
      [ "HillGenerator", "class_hill_generator.html", null ],
      [ "IslandGenerator", "class_island_generator.html", null ],
      [ "MountainGenerator", "class_mountain_generator.html", null ],
      [ "PlainGenerator", "class_plain_generator.html", null ]
    ] ],
    [ "TessellationShader", "class_tessellation_shader.html", null ],
    [ "opal::Texture", "classopal_1_1_texture.html", null ],
    [ "Texture", "struct_texture.html", null ],
    [ "TextureCreationData", "struct_texture_creation_data.html", null ],
    [ "TextureParameters", "struct_texture_parameters.html", null ],
    [ "Triangle", "struct_triangle.html", null ],
    [ "opal::VertexAttribute", "structopal_1_1_vertex_attribute.html", null ],
    [ "opal::VertexAttributeBinding", "structopal_1_1_vertex_attribute_binding.html", null ],
    [ "opal::VertexBinding", "structopal_1_1_vertex_binding.html", null ],
    [ "VertexShader", "struct_vertex_shader.html", null ],
    [ "VideoMode", "struct_video_mode.html", null ],
    [ "ViewInformation", "struct_view_information.html", null ],
    [ "VolumetricLighting", "struct_volumetric_lighting.html", null ],
    [ "WeatherState", "struct_weather_state.html", null ],
    [ "Window", "class_window.html", null ],
    [ "WindowConfiguration", "struct_window_configuration.html", null ],
    [ "Workspace", "class_workspace.html", null ],
    [ "WorleyNoise", "class_worley_noise.html", null ],
    [ "WorleyNoise3D", "class_worley_noise3_d.html", null ]
];