Atlas: photon::ProbeSpace Struct Reference
photon::ProbeSpace Struct Reference
Spatial layout and atlas packing configuration for DDGI probes.
#include <illuminate.h>
Public Member Functions
int totalProbes () const
Returns the total number of probes in the grid.
int tileResolution () const
Returns per-tile resolution including border texels.
int atlasRows () const
Returns the number of rows required by the probe atlas.
int atlasWidth () const
Returns the packed atlas width in pixels.
int atlasHeight () const
Returns the packed atlas height in pixels.
Public Attributes
Position3d originWorldSpace
World-space origin of probe index (0,0,0).
Position3d spacing
Distance between neighboring probes on each axis.
Vector3 probeCount
Probe counts along X/Y/Z axes.
Color debugColor
Debug tint used by probe visualization tools.
int textureBorderSize = 1
Border texels used around each probe tile to reduce seams.
int probeResolution = 6
Inner texel resolution per probe tile (without border).
int probesPerRow = 16
Number of probe tiles packed per atlas row.
Detailed Description
Spatial layout and atlas packing configuration for DDGI probes.
Definition at line 31 of file illuminate.h.
Member Function Documentation
atlasHeight()
int photon::ProbeSpace::atlasHeight () const inline
Returns the packed atlas height in pixels.
Definition at line 67 of file illuminate.h.
{ return atlasRows() * tileResolution(); }
References atlasRows(), and tileResolution().
atlasRows()
int photon::ProbeSpace::atlasRows () const inline
Returns the number of rows required by the probe atlas.
Definition at line 59 of file illuminate.h.
{
        return (totalProbes() + probesPerRow - 1) / probesPerRow;
    }
References probesPerRow, and totalProbes().
atlasWidth()
int photon::ProbeSpace::atlasWidth () const inline
Returns the packed atlas width in pixels.
Definition at line 64 of file illuminate.h.
{ return probesPerRow * tileResolution(); }
References probesPerRow, and tileResolution().
tileResolution()
int photon::ProbeSpace::tileResolution () const inline
Returns per-tile resolution including border texels.
Definition at line 54 of file illuminate.h.
{
        return probeResolution + (2 * textureBorderSize);
    }
References probeResolution, and textureBorderSize.
totalProbes()
int photon::ProbeSpace::totalProbes () const inline
Returns the total number of probes in the grid.
Definition at line 49 of file illuminate.h.
{
        return static_cast<int>(probeCount.x * probeCount.y * probeCount.z);
    }
References probeCount.
Member Data Documentation
debugColor
Color photon::ProbeSpace::debugColor
Debug tint used by probe visualization tools.
Definition at line 39 of file illuminate.h.
originWorldSpace
Position3d photon::ProbeSpace::originWorldSpace
World-space origin of probe index (0,0,0).
Definition at line 33 of file illuminate.h.
probeCount
Vector3 photon::ProbeSpace::probeCount
Probe counts along X/Y/Z axes.
Definition at line 37 of file illuminate.h.
probeResolution
int photon::ProbeSpace::probeResolution = 6
Inner texel resolution per probe tile (without border).
Definition at line 44 of file illuminate.h.
probesPerRow
int photon::ProbeSpace::probesPerRow = 16
Number of probe tiles packed per atlas row.
Definition at line 46 of file illuminate.h.
spacing
Position3d photon::ProbeSpace::spacing
Distance between neighboring probes on each axis.
Definition at line 35 of file illuminate.h.
textureBorderSize
int photon::ProbeSpace::textureBorderSize = 1
Border texels used around each probe tile to reduce seams.
Definition at line 42 of file illuminate.h.
The documentation for this struct was generated from the following file:
include/photon/illuminate.h