Atlas: Quaternion Struct Reference
Quaternion Struct Reference
#include <units.h>
Public Member Functions
glm::quat toGlm () const
Static Public Member Functions
static Quaternion fromGlm (const glm::quat &quat)
static Rotation3d toEuler (const Quaternion &quat)
static Quaternion fromEuler (const Rotation3d &euler)
Public Attributes
float x
float y
float z
float w
Friends
std::ostream & operator<< (std::ostream &os, const Quaternion &q)
Detailed Description
Definition at line 237 of file units.h.
Member Function Documentation
fromEuler()
Quaternion Quaternion::fromEuler (const Rotation3d & euler) inline static
Definition at line 259 of file units.h.
{
        return fromGlm(euler.toGlmQuat());
    }
References fromGlm(), and Rotation3d::toGlmQuat().
fromGlm()
Quaternion Quaternion::fromGlm (const glm::quat & quat) inline static
Definition at line 245 of file units.h.
{
        return {.x = quat.x, .y = quat.y, .z = quat.z, .w = quat.w};
    }
toEuler()
Rotation3d Quaternion::toEuler (const Quaternion & quat) inline static
Definition at line 255 of file units.h.
{
        return Rotation3d::fromGlmQuat(quat.toGlm());
    }
References Rotation3d::fromGlmQuat(), and toGlm().
toGlm()
glm::quat Quaternion::toGlm () const inline
Definition at line 243 of file units.h.
{ return glm::quat(w, x, y, z); }
References w, x, y, and z.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Quaternion & q) friend
Definition at line 249 of file units.h.
{
        os << "Quaternion(" << q.x << ", " << q.y << ", " << q.z << ", " << q.w
           << ")";
        return os;
    }
References w, x, y, and z.
Member Data Documentation
w
float Quaternion::w
Definition at line 241 of file units.h.
x
float Quaternion::x
Definition at line 238 of file units.h.
y
float Quaternion::y
Definition at line 239 of file units.h.
z
float Quaternion::z
Definition at line 240 of file units.h.
The documentation for this struct was generated from the following file:
include/atlas/units.h