Atlas: Rotation3d Struct Reference
Rotation3d Struct Reference
Structure representing rotation in 3D space using Euler angles. Provides arithmetic operations and conversions to/from GLM quaternions.
#include <units.h>
Public Member Functions
Rotation3d ()
Rotation3d (float pitch, float yaw, float roll)
Rotation3d (double pitch, double yaw, double roll)
Rotation3d operator+ (const Rotation3d &other) const
Rotation3d operator- (const Rotation3d &other) const
Rotation3d operator* (float scalar) const
bool operator== (const Rotation3d &other) const
Rotation3d operator/ (float scalar) const
glm::vec3 toGlm () const
glm::quat toGlmQuat () const
Static Public Member Functions
static Rotation3d fromGlmQuat (const glm::quat &quat)
static Rotation3d fromGlm (const glm::vec3 &vec)
Public Attributes
float pitch
float yaw
float roll
Detailed Description
Structure representing rotation in 3D space using Euler angles. Provides arithmetic operations and conversions to/from GLM quaternions.
Example
// Create a rotation (pitch, yaw, roll in degrees)
Rotation3d rot(0.0f, 45.0f, 0.0f);
// Rotate object over time
rot.yaw += deltaTime * 90.0f; // 90 degrees per second
// Convert to quaternion for rendering
glm::quat quatRot = rot.toGlmQuat();
Definition at line 143 of file units.h.
Constructor & Destructor Documentation
Rotation3d() [1/3]
Rotation3d::Rotation3d () inline
Definition at line 148 of file units.h.
: pitch(0.0f), yaw(0.0f), roll(0.0f) {}
References pitch, roll, and yaw.
Rotation3d() [2/3]
Rotation3d::Rotation3d (float pitch, float yaw, float roll) inline
Definition at line 150 of file units.h.
        : pitch(pitch), yaw(yaw), roll(roll) {}
References pitch, roll, and yaw.
Rotation3d() [3/3]
Rotation3d::Rotation3d (double pitch, double yaw, double roll) inline
Definition at line 153 of file units.h.
        : pitch(static_cast<float>(pitch)), yaw(static_cast<float>(yaw)),
          roll(static_cast<float>(roll)) {}
References pitch, roll, and yaw.
Member Function Documentation
fromGlm()
Rotation3d Rotation3d::fromGlm (const glm::vec3 & vec) inline static
Definition at line 190 of file units.h.
{
        return {vec.x, vec.y, vec.z};
    }
References Rotation3d().
fromGlmQuat()
Rotation3d Rotation3d::fromGlmQuat (const glm::quat & quat) inline static
Definition at line 185 of file units.h.
{
        glm::vec3 euler = glm::degrees(glm::eulerAngles(quat));
        return {euler.x, euler.y, euler.z};
    }
References Rotation3d().
operator*()
Rotation3d Rotation3d::operator* (float scalar) const inline
Definition at line 165 of file units.h.
{
        return {pitch * scalar, yaw * scalar, roll * scalar};
    }
References pitch, roll, Rotation3d(), and yaw.
operator+()
Rotation3d Rotation3d::operator+ (const Rotation3d & other) const inline
Definition at line 157 of file units.h.
{
        return {pitch + other.pitch, yaw + other.yaw, roll + other.roll};
    }
References pitch, roll, Rotation3d(), and yaw.
operator-()
Rotation3d Rotation3d::operator- (const Rotation3d & other) const inline
Definition at line 161 of file units.h.
{
        return {pitch - other.pitch, yaw - other.yaw, roll - other.roll};
    }
References pitch, roll, Rotation3d(), and yaw.
operator/()
Rotation3d Rotation3d::operator/ (float scalar) const inline
Definition at line 173 of file units.h.
{
        return {pitch / scalar, yaw / scalar, roll / scalar};
    }
References pitch, roll, Rotation3d(), and yaw.
operator==()
bool Rotation3d::operator== (const Rotation3d & other) const inline
Definition at line 169 of file units.h.
{
        return pitch == other.pitch && yaw == other.yaw && roll == other.roll;
    }
References pitch, roll, Rotation3d(), and yaw.
toGlm()
glm::vec3 Rotation3d::toGlm () const inline
Definition at line 177 of file units.h.
{ return glm::vec3(pitch, yaw, roll); }
References pitch, roll, and yaw.
toGlmQuat()
glm::quat Rotation3d::toGlmQuat () const inline
Definition at line 179 of file units.h.
{
        glm::vec3 eulerAngles = toGlm();
        glm::vec3 radians = glm::radians(eulerAngles);
        return glm::quat(radians);
    }
References toGlm().
Member Data Documentation
pitch
float Rotation3d::pitch
Definition at line 144 of file units.h.
roll
float Rotation3d::roll
Definition at line 146 of file units.h.
yaw
float Rotation3d::yaw
Definition at line 145 of file units.h.
The documentation for this struct was generated from the following file:
include/atlas/units.h