Atlas: Position3d Struct Reference
Position3d Struct Reference
Structure representing a position in 3D space with double precision. Provides arithmetic operations and conversions to/from GLM types.
#include <units.h>
Public Member Functions
Position3d ()
Position3d (float x, float y, float z)
Position3d (double x, double y, double z)
Position3d operator+ (const Position3d &other) const
Position3d operator- (const Position3d &other) const
Position3d operator* (float scalar) const
Position3d operator/ (float scalar) const
bool operator== (const Position3d &other) const
glm::vec3 toGlm () const
Position3d operator+ (const glm::vec3 &vec) const
Position3d operator- (const glm::vec3 &vec) const
void operator+= (const Position3d &vec)
void operator-= (const Position3d &vec)
Position3d normalized () const
Static Public Member Functions
static Position3d fromGlm (const glm::vec3 &vec)
Public Attributes
float x
float y
float z
Friends
std::ostream & operator<< (std::ostream &os, const Position3d &p)
Detailed Description
Structure representing a position in 3D space with double precision. Provides arithmetic operations and conversions to/from GLM types.
Example
// Create a position
Position3d pos(10.0f, 5.0f, -3.0f);
// Move it
pos += Position3d(1.0f, 0.0f, 0.0f);
// Convert to GLM vector for rendering
glm::vec3 glmPos = pos.toGlm();
Definition at line 32 of file units.h.
Constructor & Destructor Documentation
Position3d() [1/3]
Position3d::Position3d () inline
Definition at line 37 of file units.h.
: x(0.0f), y(0.0f), z(0.0f) {}
References x, y, and z.
Position3d() [2/3]
Position3d::Position3d (float x, float y, float z) inline
Definition at line 38 of file units.h.
: x(x), y(y), z(z) {}
References x, y, and z.
Position3d() [3/3]
Position3d::Position3d (double x, double y, double z) inline
Definition at line 39 of file units.h.
        : x(static_cast<float>(x)), y(static_cast<float>(y)),
          z(static_cast<float>(z)) {}
References x, y, and z.
Member Function Documentation
fromGlm()
Position3d Position3d::fromGlm (const glm::vec3 & vec) inline static
Definition at line 92 of file units.h.
{
        return {vec.x, vec.y, vec.z};
    };
References Position3d().
normalized()
Position3d Position3d::normalized () const inline
Definition at line 85 of file units.h.
{
        float length = std::sqrt(x * x + y * y + z * z);
        if (length == 0)
            return {};
        return {x / length, y / length, z / length};
    }
References Position3d(), x, y, and z.
operator*()
Position3d Position3d::operator* (float scalar) const inline
Definition at line 51 of file units.h.
{
        return {x * scalar, y * scalar, z * scalar};
    }
References Position3d(), x, y, and z.
operator+() [1/2]
Position3d Position3d::operator+ (const glm::vec3 & vec) const inline
Definition at line 65 of file units.h.
{
        return {x + vec.x, y + vec.y, z + vec.z};
    }
References Position3d(), x, y, and z.
operator+() [2/2]
Position3d Position3d::operator+ (const Position3d & other) const inline
Definition at line 43 of file units.h.
{
        return {x + other.x, y + other.y, z + other.z};
    }
References Position3d(), x, y, and z.
operator+=()
void Position3d::operator+= (const Position3d & vec) inline
Definition at line 73 of file units.h.
{
        x += vec.x;
        y += vec.y;
        z += vec.z;
    }
References Position3d(), x, y, and z.
operator-() [1/2]
Position3d Position3d::operator- (const glm::vec3 & vec) const inline
Definition at line 69 of file units.h.
{
        return {x - vec.x, y - vec.y, z - vec.z};
    }
References Position3d(), x, y, and z.
operator-() [2/2]
Position3d Position3d::operator- (const Position3d & other) const inline
Definition at line 47 of file units.h.
{
        return {x - other.x, y - other.y, z - other.z};
    }
References Position3d(), x, y, and z.
operator-=()
void Position3d::operator-= (const Position3d & vec) inline
Definition at line 79 of file units.h.
{
        x -= vec.x;
        y -= vec.y;
        z -= vec.z;
    }
References Position3d(), x, y, and z.
operator/()
Position3d Position3d::operator/ (float scalar) const inline
Definition at line 55 of file units.h.
{
        return {x / scalar, y / scalar, z / scalar};
    }
References Position3d(), x, y, and z.
operator==()
bool Position3d::operator== (const Position3d & other) const inline
Definition at line 59 of file units.h.
{
        return x == other.x && y == other.y && z == other.z;
    }
References Position3d(), x, y, and z.
toGlm()
glm::vec3 Position3d::toGlm () const inline
Definition at line 63 of file units.h.
{ return glm::vec3(x, y, z); }
References x, y, and z.
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & os, const Position3d & p) friend
Definition at line 96 of file units.h.
{
        os << "Position3d(" << p.x << ", " << p.y << ", " << p.z << ")";
        return os;
    }
References Position3d(), x, y, and z.
Member Data Documentation
x
float Position3d::x
Definition at line 33 of file units.h.
y
float Position3d::y
Definition at line 34 of file units.h.
z
float Position3d::z
Definition at line 35 of file units.h.
The documentation for this struct was generated from the following file:
include/atlas/units.h