use colored::Colorize;
use std::{path::Path, process::Command};

pub fn lsp() {
    println!(
        "{}",
        "Generating compile_commands.json for LSP..."
            .italic()
            .yellow()
    );

    let build_dir = Path::new("build");
    if !build_dir.exists() {
        std::fs::create_dir(build_dir).expect("Failed to create build directory");
        println!("{}", "Created build directory.".italic().cyan());
    }

    let mut configure_cmd = Command::new("cmake");
    configure_cmd
        .current_dir(build_dir)
        .arg("..")
        .arg("-DCMAKE_EXPORT_COMPILE_COMMANDS=ON")
        .arg("-DCMAKE_BUILD_TYPE=Debug");

    let output = configure_cmd
        .output()
        .expect("Failed to execute cmake command");

    if !output.status.success() {
        eprintln!("{}", "CMake configuration failed!".italic().red());
        eprintln!("{}", String::from_utf8_lossy(&output.stderr));
        return;
    }

    println!("{}", "CMake configuration successful!".italic().green());

    let compile_commands_src = build_dir.join("compile_commands.json");
    let compile_commands_dest = Path::new("compile_commands.json");

    if compile_commands_src.exists() {
        std::fs::copy(&compile_commands_src, compile_commands_dest)
            .expect("Failed to copy compile_commands.json to project root");
        println!(
            "{}",
            "compile_commands.json generated and copied to project root!"
                .italic()
                .green()
        );
    } else {
        eprintln!(
            "{}",
            "compile_commands.json was not generated by CMake."
                .italic()
                .red()
        );
    }
}
