name: Format CLI
on:
  push:
  pull_request:

jobs:
  format_cli:
    name: format_cli
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
